<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>results – STYCS P-Kinetics Manuscript</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-f33fce411228158d07e3e7295642fce5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">STYCS P-Kinetics Manuscript</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Manuscript</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#results" id="toc-results" class="nav-link active" data-scroll-target="#results"><span class="header-section-number">1</span> Results</a>
  <ul class="collapse">
  <li><a href="#establishment-of-the-p-desorption-kinetic-model" id="toc-establishment-of-the-p-desorption-kinetic-model" class="nav-link" data-scroll-target="#establishment-of-the-p-desorption-kinetic-model"><span class="header-section-number">1.1</span> Establishment of the P-Desorption Kinetic Model</a>
  <ul class="collapse">
  <li><a href="#initial-approach-failure-of-the-linearized-model" id="toc-initial-approach-failure-of-the-linearized-model" class="nav-link" data-scroll-target="#initial-approach-failure-of-the-linearized-model"><span class="header-section-number">1.1.1</span> Initial Approach: Failure of the Linearized Model</a></li>
  <li><a href="#final-approach-successful-non-linear-model" id="toc-final-approach-successful-non-linear-model" class="nav-link" data-scroll-target="#final-approach-successful-non-linear-model"><span class="header-section-number">1.1.2</span> Final Approach: Successful Non-Linear Model</a></li>
  </ul></li>
  <li><a href="#comparison-with-isotopic-exchange-kinetics-iek" id="toc-comparison-with-isotopic-exchange-kinetics-iek" class="nav-link" data-scroll-target="#comparison-with-isotopic-exchange-kinetics-iek"><span class="header-section-number">1.2</span> Comparison with Isotopic Exchange Kinetics (IEK)</a></li>
  <li><a href="#sec-effects-of-fertilization-on-agronomic-and-soil-parameters" id="toc-sec-effects-of-fertilization-on-agronomic-and-soil-parameters" class="nav-link" data-scroll-target="#sec-effects-of-fertilization-on-agronomic-and-soil-parameters"><span class="header-section-number">1.3</span> Effects of Fertilization on Agronomic and Soil Parameters</a>
  <ul class="collapse">
  <li><a href="#sec-agronomic-responses-to-p-fertilization" id="toc-sec-agronomic-responses-to-p-fertilization" class="nav-link" data-scroll-target="#sec-agronomic-responses-to-p-fertilization"><span class="header-section-number">1.3.1</span> Agronomic Responses to P Fertilization</a></li>
  <li><a href="#sec-soil-p-parameters-as-a-function-of-p-fertilization" id="toc-sec-soil-p-parameters-as-a-function-of-p-fertilization" class="nav-link" data-scroll-target="#sec-soil-p-parameters-as-a-function-of-p-fertilization"><span class="header-section-number">1.3.2</span> Soil P Parameters as a Function of P Fertilization</a></li>
  </ul></li>
  <li><a href="#sec-p-params-soil-props" id="toc-sec-p-params-soil-props" class="nav-link" data-scroll-target="#sec-p-params-soil-props"><span class="header-section-number">1.4</span> Predicting P Parameters from Soil Properties</a></li>
  <li><a href="#sec-agronomic-modeling" id="toc-sec-agronomic-modeling" class="nav-link" data-scroll-target="#sec-agronomic-modeling"><span class="header-section-number">1.5</span> Predictive Modeling of Agronomic Outcomes</a>
  <ul class="collapse">
  <li><a href="#anomaly-in-the-cadenazzo-yield-data" id="toc-anomaly-in-the-cadenazzo-yield-data" class="nav-link" data-scroll-target="#anomaly-in-the-cadenazzo-yield-data"><span class="header-section-number">1.5.1</span> Anomaly in the Cadenazzo Yield Data</a></li>
  <li><a href="#predicting-site-normalized-yield-y_norm" id="toc-predicting-site-normalized-yield-y_norm" class="nav-link" data-scroll-target="#predicting-site-normalized-yield-y_norm"><span class="header-section-number">1.5.2</span> Predicting Site-Normalized Yield (<span class="math inline">\(Y_{norm}\)</span>)</a></li>
  <li><a href="#predicting-national-normalized-yield-y_rel" id="toc-predicting-national-normalized-yield-y_rel" class="nav-link" data-scroll-target="#predicting-national-normalized-yield-y_rel"><span class="header-section-number">1.5.3</span> Predicting National-Normalized Yield (<span class="math inline">\(Y_{rel}\)</span>)</a></li>
  <li><a href="#predicting-p-uptake-p_up" id="toc-predicting-p-uptake-p_up" class="nav-link" data-scroll-target="#predicting-p-uptake-p_up"><span class="header-section-number">1.5.4</span> Predicting P-Uptake (<span class="math inline">\(P_{up}\)</span>)</a></li>
  <li><a href="#predicting-p-balance-p_bal" id="toc-predicting-p-balance-p_bal" class="nav-link" data-scroll-target="#predicting-p-balance-p_bal"><span class="header-section-number">1.5.5</span> Predicting P-Balance (<span class="math inline">\(P_{bal}\)</span>)</a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="25-results.docx"><i class="bi bi-file-word"></i>MS Word</a></li><li><a href="25-results.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="results" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Results</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>create_coef_table <span class="ot">&lt;-</span> <span class="cf">function</span>(lmer_models, </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">covariate_order =</span> <span class="cn">NULL</span>, </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">covariate_labels =</span> <span class="cn">NULL</span>, <span class="co"># NEU: Benannter Vektor für Zeilennamen</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>                              <span class="at">model_labels =</span> <span class="cn">NULL</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>                              <span class="at">descriptor =</span> <span class="st">"Response"</span>) {   <span class="co"># NEU: Benannter Vektor für Spaltennamen</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Extract coefficients and p-values (Ihre Originalfunktion, keine Änderung hier)</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  extract_coef_info <span class="ot">&lt;-</span> <span class="cf">function</span>(model) {</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># ... (keine Änderung, Ihr Code bleibt hier)</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    coef_matrix <span class="ot">&lt;-</span> <span class="fu">summary</span>(model)<span class="sc">|&gt;</span> <span class="fu">coef</span>()</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    estimates <span class="ot">&lt;-</span> coef_matrix[, <span class="dv">1</span>]</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    p_values <span class="ot">&lt;-</span> coef_matrix[, <span class="fu">ncol</span>(coef_matrix)]</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    formatted_coef <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="fu">seq_along</span>(estimates), <span class="cf">function</span>(i) {</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>      est_str <span class="ot">&lt;-</span> <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, estimates[i])</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>      stars <span class="ot">&lt;-</span> <span class="cf">if</span> (p_values[i] <span class="sc">&lt;</span> <span class="fl">0.001</span>) <span class="st">"***"</span> <span class="cf">else</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>               <span class="cf">if</span> (p_values[i] <span class="sc">&lt;</span> <span class="fl">0.01</span>) <span class="st">"** "</span> <span class="cf">else</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>               <span class="cf">if</span> (p_values[i] <span class="sc">&lt;</span> <span class="fl">0.05</span>) <span class="st">"* "</span> <span class="cf">else</span>  <span class="st">""</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>      <span class="fu">paste0</span>(est_str,stars)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">names</span>(formatted_coef) <span class="ot">&lt;-</span> <span class="fu">rownames</span>(coef_matrix)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(formatted_coef)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Extract R-squared values (Ihre Originalfunktion, keine Änderung hier)</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>  extract_r_squared <span class="ot">&lt;-</span> <span class="cf">function</span>(model) {</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    <span class="co"># ... (keine Änderung, Ihr Code bleibt hier)</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    r2_values <span class="ot">&lt;-</span> MuMIn<span class="sc">::</span><span class="fu">r.squaredGLMM</span>(model) <span class="co"># MuMIn:: hinzugefügt für Klarheit</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">c</span>(</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>      <span class="at">R2m =</span> <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, r2_values[<span class="dv">1</span>, <span class="st">"R2m"</span>]),</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>      <span class="at">R2c =</span> <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, r2_values[<span class="dv">1</span>, <span class="st">"R2c"</span>])</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>    ))</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Daten extrahieren (Ihr Originalcode)</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>  all_coefs <span class="ot">&lt;-</span> <span class="fu">lapply</span>(lmer_models, extract_coef_info)</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>  all_r_squared <span class="ot">&lt;-</span> <span class="fu">lapply</span>(lmer_models, extract_r_squared)</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>  all_covariate_names <span class="ot">&lt;-</span> <span class="fu">unique</span>(<span class="fu">unlist</span>(<span class="fu">lapply</span>(all_coefs, names)))</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">is.null</span>(covariate_order)) {</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>    covariate_order <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"(Intercept)"</span>, <span class="fu">sort</span>(all_covariate_names[all_covariate_names <span class="sc">!=</span> <span class="st">"(Intercept)"</span>]))</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>  covariate_order <span class="ot">&lt;-</span> covariate_order[covariate_order <span class="sc">%in%</span> all_covariate_names]</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>  final_order <span class="ot">&lt;-</span> <span class="fu">c</span>(covariate_order, <span class="st">"R2m"</span>, <span class="st">"R2c"</span>)</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Matrix erstellen (Ihr Originalcode)</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>  results_matrix <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="st">""</span>,</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>                           <span class="at">nrow =</span> <span class="fu">length</span>(final_order),</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>                           <span class="at">ncol =</span> <span class="fu">length</span>(lmer_models),</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>                           <span class="at">dimnames =</span> <span class="fu">list</span>(final_order, <span class="fu">names</span>(lmer_models)))</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Matrix füllen (Ihr Originalcode)</span></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (model_name <span class="cf">in</span> <span class="fu">names</span>(lmer_models)) {</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>    model_coefs <span class="ot">&lt;-</span> all_coefs[[model_name]]</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> (covar <span class="cf">in</span> <span class="fu">names</span>(model_coefs)) {</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> (covar <span class="sc">%in%</span> covariate_order) {</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>        results_matrix[covar, model_name] <span class="ot">&lt;-</span> model_coefs[covar]</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>      }</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>    r2_values <span class="ot">&lt;-</span> all_r_squared[[model_name]]</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>    results_matrix[<span class="st">"R2m"</span>, model_name] <span class="ot">&lt;-</span> r2_values[<span class="st">"R2m"</span>]</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>    results_matrix[<span class="st">"R2c"</span>, model_name] <span class="ot">&lt;-</span> r2_values[<span class="st">"R2c"</span>]</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>  <span class="co"># --- NEU: Zeilen- und Spaltennamen ersetzen ---</span></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Ersetze die Zeilennamen (Kovariaten), falls covariate_labels übergeben wurde</span></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(covariate_labels)) {</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Finde die Übereinstimmungen in den aktuellen Zeilennamen</span></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>    row_matches <span class="ot">&lt;-</span> <span class="fu">match</span>(<span class="fu">rownames</span>(results_matrix), <span class="fu">names</span>(covariate_labels))</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Ersetze nur die, die gefunden wurden</span></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>    new_rownames <span class="ot">&lt;-</span> <span class="fu">rownames</span>(results_matrix)</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>    new_rownames[<span class="sc">!</span><span class="fu">is.na</span>(row_matches)] <span class="ot">&lt;-</span> covariate_labels[row_matches[<span class="sc">!</span><span class="fu">is.na</span>(row_matches)]]</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rownames</span>(results_matrix) <span class="ot">&lt;-</span> new_rownames</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Ersetze die Spaltennamen (Modelle), falls model_labels übergeben wurde</span></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(model_labels)) {</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>    col_matches <span class="ot">&lt;-</span> <span class="fu">match</span>(<span class="fu">colnames</span>(results_matrix), <span class="fu">names</span>(model_labels))</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>    new_colnames <span class="ot">&lt;-</span> <span class="fu">colnames</span>(results_matrix)</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>    new_colnames[<span class="sc">!</span><span class="fu">is.na</span>(col_matches)] <span class="ot">&lt;-</span> model_labels[col_matches[<span class="sc">!</span><span class="fu">is.na</span>(col_matches)]]</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>    <span class="fu">colnames</span>(results_matrix) <span class="ot">&lt;-</span> new_colnames</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>  <span class="co"># --- Ende der neuen Sektion ---</span></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Convert to data frame for kable</span></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>  results_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="st">"Predictor"</span> <span class="ot">=</span> <span class="fu">rownames</span>(results_matrix),</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>                           results_matrix,</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>                           <span class="at">check.names =</span> <span class="cn">FALSE</span>, <span class="co"># Verhindert, dass R Spaltennamen ändert</span></span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>                           <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>  results_df</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The results of this study are presented in two main parts. First, the development and validation of the phosphorus (P) desorption kinetic model are detailed, justifying the final modeling approach. Second, the descriptive trends of both agronomic outcomes and soil P parameters in response to long-term fertilization and site differences are explored visually. Finally, the predictive power of the kinetic and standard P parameters is formally evaluated using linear mixed-effects models.</p>
<section id="establishment-of-the-p-desorption-kinetic-model" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="establishment-of-the-p-desorption-kinetic-model"><span class="header-section-number">1.1</span> Establishment of the P-Desorption Kinetic Model</h2>
<p>The primary goal was to derive two key parameters for each soil sample: the desorbable P pool (<span class="math inline">\(P_{desorb}\)</span>) and the rate constant (<span class="math inline">\(k\)</span>). The analysis proceeded in two stages: an initial test of a linearized model, followed by the implementation of a more robust non-linear model.</p>
<section id="initial-approach-failure-of-the-linearized-model" class="level3" data-number="1.1.1">
<h3 data-number="1.1.1" class="anchored" data-anchor-id="initial-approach-failure-of-the-linearized-model"><span class="header-section-number">1.1.1</span> Initial Approach: Failure of the Linearized Model</h3>
<p>Following the conceptual framework of Flossmann and Richter (1982), the first-order kinetic equation was linearized. A core assumption of this model is that the linear relationship must pass through the origin (0/0) of the coordinate system. To test this, linear models were fitted to the transformed data for each sample individually. The results revealed a systematic failure of this assumption, as the estimated intercepts for the majority of samples were highly significantly different from zero (p &lt; 0.05). This consistent statistical deviation indicated that the linearized approach was not a valid representation of the data. The visual evidence in <a href="#fig-linearized-model" class="quarto-xref">Figure&nbsp;1</a> supports this conclusion.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-linearized-model" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-linearized-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="25-results_files/figure-html/fig-linearized-model-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-linearized-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Test of the linearized first-order kinetic model. The plot visually supports the statistical finding that many intercepts are not zero.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="final-approach-successful-non-linear-model" class="level3" data-number="1.1.2">
<h3 data-number="1.1.2" class="anchored" data-anchor-id="final-approach-successful-non-linear-model"><span class="header-section-number">1.1.2</span> Final Approach: Successful Non-Linear Model</h3>
<p>Given the statistical failure of the linearized model, a direct non-linear modeling approach was adopted to estimate both <span class="math inline">\(P_{desorb}\)</span> and <span class="math inline">\(k\)</span> simultaneously from the untransformed data. This approach does not rely on the assumption of a zero intercept and proved to be far more successful, accurately capturing the curvilinear shape of the desorption data for nearly all samples (<a href="#fig-nonlinear-model" class="quarto-xref">Figure&nbsp;2</a>). The final parameters were extracted from a non-linear mixed-effects model (<code>nlme</code>) to account for the hierarchical data structure. <strong>These final <code>nlme</code>-derived coefficients were used for all subsequent analyses.</strong></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-nonlinear-model" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nonlinear-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="25-results_files/figure-html/fig-nonlinear-model-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nonlinear-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Non-linear first-order kinetic model fits for P desorption over time. Points represent measured data and solid lines represent the fitted model for each replicate.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="comparison-with-isotopic-exchange-kinetics-iek" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="comparison-with-isotopic-exchange-kinetics-iek"><span class="header-section-number">1.2</span> Comparison with Isotopic Exchange Kinetics (IEK)</h2>
<p>To validate the newly derived kinetic parameters against an established benchmark, the capacity (<span class="math inline">\(P_{desorb}\)</span>) and kinetic (<span class="math inline">\(k\)</span>) parameters were compared to data from Isotopic Exchange Kinetics (IEK) studies previously conducted on the same long-term trial sites by Demaria et al.&nbsp;(2013). This comparison aims to determine if the simpler, non-equilibrium desorption method used in this thesis captures similar aspects of soil P dynamics as the more complex, equilibrium-based IEK method.</p>
<p>The size of the desorbable P pool (<span class="math inline">\(P_{desorb}\)</span>) was compared against the long-term isotopically exchangeable P pool measured after 7 days (<span class="math inline">\(E_{7d}\)</span>). The desorption rate constant (<span class="math inline">\(k\)</span>) was compared against the IEK kinetic parameter measured after 24 hours (<span class="math inline">\(n_{1d}\)</span>). Spearman’s rank correlation was used to robustly test for monotonic trends between the different methods.</p>
<div id="fig-iek-comparison" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-iek-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-iek-comparison" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-iek-comparison-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-iek-comparison-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="25-results_files/figure-html/fig-iek-comparison-1.png" class="img-fluid figure-img" data-ref-parent="fig-iek-comparison">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-iek-comparison-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Capacity: <span class="math inline">\(P_{\text{desorb}}\)</span> vs <span class="math inline">\(E_{\text{7d}}\)</span>
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-iek-comparison" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-iek-comparison-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-iek-comparison-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="25-results_files/figure-html/fig-iek-comparison-2.png" class="img-fluid figure-img" data-ref-parent="fig-iek-comparison">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-iek-comparison-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Kinetics: k vs <span class="math inline">\(n_{\text{1d}}\)</span>
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-iek-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Correlation between desorption-derived kinetic parameters and IEK-derived parameters. (A) Capacity parameters: Desorbable P (<span class="math inline">\(P_{\text{desorb}}\)</span>) vs.&nbsp;Isotopically Exchangeable P (<span class="math inline">\(E_{\text{7d}}\)</span>). (B) Kinetic parameters: Rate Constant (<span class="math inline">\(k\)</span>) vs.&nbsp;IEK kinetic parameter (<span class="math inline">\(n_{\text{1d}}\)</span>).
</figcaption>
</figure>
</div>
<p>The analysis revealed a statistically significant, moderate positive correlation between the capacity parameters, <span class="math inline">\(P_{desorb}\)</span> and <span class="math inline">\(E_{7d}\)</span> (<a href="#fig-iek-comparison" class="quarto-xref">Figure&nbsp;3</a>). The Spearman’s rank correlation coefficient was 0.4 with a p-value of &lt; 0.001.</p>
<p>Similarly, a statistically significant, moderate positive correlation was found between the kinetic parameters, <span class="math inline">\(k\)</span> and <span class="math inline">\(n_{1d}\)</span> (<a href="#fig-iek-comparison" class="quarto-xref">Figure&nbsp;3</a>). The Spearman’s rank correlation coefficient was 0.36 with a p-value of &lt; 0.001.</p>
<p>These results indicate that the simpler, non-equilibrium desorption method used in this study successfully captures both the capacity and intensity aspects of soil P lability, providing results that are consistent with the more complex, equilibrium-based IEK method reported by <span class="citation" data-cites="demariaSoilPropertiesPhosphorus2013">(<a href="#ref-demariaSoilPropertiesPhosphorus2013" role="doc-biblioref">Demaria et al., 2013</a>)</span>.</p>
</section>
<section id="sec-effects-of-fertilization-on-agronomic-and-soil-parameters" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="sec-effects-of-fertilization-on-agronomic-and-soil-parameters"><span class="header-section-number">1.3</span> Effects of Fertilization on Agronomic and Soil Parameters</h2>
<p>Having established a robust method to determine the kinetic parameters, the next step was to explore the effects of the long-term P fertilization treatments on both the agronomic outcomes and the soil P test parameters.</p>
<section id="sec-agronomic-responses-to-p-fertilization" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="sec-agronomic-responses-to-p-fertilization"><span class="header-section-number">1.3.1</span> Agronomic Responses to P Fertilization</h3>
<p>The long-term application of different P fertilization levels had a pronounced impact on the primary agronomic outcomes, including two different metrics for yield, P Uptake (<span class="math inline">\(P_{up}\)</span>), and P Balance (<span class="math inline">\(P_{bal}\)</span>), though the response varied considerably between sites (<a href="#fig-agronomic-responses" class="quarto-xref">Figure&nbsp;4</a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-agronomic-responses" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-agronomic-responses-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="25-results_files/figure-html/fig-agronomic-responses-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-agronomic-responses-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Agronomic response variables across six P fertilization treatments and six experimental sites. Data from 2017-2022.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Yield Metrics (</strong><span class="math inline">\(Y_{norm}\)</span> and <span class="math inline">\(Y_{rel}\)</span>): Both yield metrics showed a generally positive response to P fertilization. The site-normalized yield (<span class="math inline">\(Y_{norm}\)</span>) shows the response relative to the site’s potential for that year, with most yields plateauing around the Norm (100%) treatment. The national-normalized yield (<span class="math inline">\(Y_{rel}\)</span>) provides a broader context, showing how yields at each site compare to the national average.</p>
<p><strong>P Uptake (</strong><span class="math inline">\(P_{up}\)</span>): P uptake by crops followed a similar trend to yield, increasing with fertilization, often continuing to increase at the highest fertilization levels, suggesting luxury consumption.</p>
<p><strong>P Balance (</strong><span class="math inline">\(P_{bal}\)</span>): The P balance showed a strong, linear relationship with fertilization. The Zero and Deficit treatments resulted in a negative balance (mining soil P), while the Elevated and Surplus treatments led to a significant P surplus.</p>
</section>
<section id="sec-soil-p-parameters-as-a-function-of-p-fertilization" class="level3" data-number="1.3.2">
<h3 data-number="1.3.2" class="anchored" data-anchor-id="sec-soil-p-parameters-as-a-function-of-p-fertilization"><span class="header-section-number">1.3.2</span> Soil P Parameters as a Function of P Fertilization</h3>
<p>The different soil P test parameters, including the standard STP methods and the newly derived kinetic parameters, all responded to the long-term fertilization treatments (<a href="#fig-soil-parameters" class="quarto-xref">Figure&nbsp;5</a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-soil-parameters" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-soil-parameters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="25-results_files/figure-html/fig-soil-parameters-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-soil-parameters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Soil P parameters across six P fertilization treatments and six experimental sites.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Standard STPs (</strong><span class="math inline">\(P_{CO_2}\)</span> and <span class="math inline">\(P_{AAE10}\)</span>): Both standard soil P tests showed a clear and consistent increase with rising P fertilization levels across all sites, confirming their sensitivity to management.</p>
<p><strong>Kinetic Parameters (</strong><span class="math inline">\(k\)</span>, <span class="math inline">\(P_{desorb}\)</span>, and <span class="math inline">\(J_0\)</span>): <strong>Desorbable P (</strong><span class="math inline">\(P_{desorb}\)</span>): This parameter behaved very similarly to the standard STPs, increasing steadily with P fertilization and confirming its role as a “capacity” indicator.<br>
<strong>Rate Constant (</strong><span class="math inline">\(k\)</span>): The rate constant showed a more complex pattern, with no strong, consistent trend with fertilization. This suggests that while fertilization increases the <em>amount</em> of available P, it may not change the intrinsic <em>release rate</em>. <strong>Initial P Flux (</strong><span class="math inline">\(J_0\)</span>): As the product of <span class="math inline">\(P_{desorb}\)</span> and <span class="math inline">\(k\)</span>, this parameter integrates both capacity and intensity. It showed a strong positive response to fertilization, driven primarily by the increase in <span class="math inline">\(P_{desorb}\)</span>.</p>
<p>These initial observations suggest that the kinetic parameters, particularly the rate constant <span class="math inline">\(k\)</span>, may provide unique information about the soil’s P dynamics not captured by the static tests P-CO2 and P-AAE10 alone. The next section will use formal statistical models to test these relationships.</p>
</section>
</section>
<section id="sec-p-params-soil-props" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="sec-p-params-soil-props"><span class="header-section-number">1.4</span> Predicting P Parameters from Soil Properties</h2>
<p>To understand the underlying drivers of the standard and kinetic P parameters, and to test <strong>Hypotheses 1b and 2b</strong>, a series of linear mixed-effects models were fitted. Each model predicted one of the P parameters based on the core soil properties: organic carbon (<span class="math inline">\(C_{org}\)</span>), clay content, silt content, pH, and dithionite-extractable Al (<span class="math inline">\(Al_d\)</span>) and Fe (<span class="math inline">\(Fe_d\)</span>). The results are summarized in <a href="#tbl-soil-prop-models" class="quarto-xref">Table&nbsp;1</a>.</p>
<div class="cell">
<div id="tbl-soil-prop-models" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-soil-prop-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Results of linear mixed-effects models predicting P parameters from intrinsic soil properties <strong>?@tbl-variables</strong>. Significance codes: ‘<em><strong>’ p &lt; 0.001, ’</strong>’ p &lt; 0.01, ’</em>’ p &lt; 0.05.
</figcaption>
<div aria-describedby="tbl-soil-prop-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 15%">
<col style="width: 19%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 16%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Predictor</th>
<th style="text-align: left;"><span class="math inline">\(P_{desorb}\)</span></th>
<th style="text-align: left;"><span class="math inline">\(k\)</span></th>
<th style="text-align: left;"><span class="math inline">\(J_0\)</span></th>
<th style="text-align: left;"><span class="math inline">\(P_{CO_2}\)</span></th>
<th style="text-align: left;"><span class="math inline">\(P_{AAE10}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: left;">21.444</td>
<td style="text-align: left;">0.454</td>
<td style="text-align: left;">21.189</td>
<td style="text-align: left;">14.014</td>
<td style="text-align: left;">23.126</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(Al_{d}\)</span></td>
<td style="text-align: left;">-8.706***</td>
<td style="text-align: left;">-0.072***</td>
<td style="text-align: left;">-8.631***</td>
<td style="text-align: left;">-4.417***</td>
<td style="text-align: left;">-9.473***</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(Fe_{d}\)</span></td>
<td style="text-align: left;">-1.068***</td>
<td style="text-align: left;">0.005</td>
<td style="text-align: left;">-1.084***</td>
<td style="text-align: left;">-0.845***</td>
<td style="text-align: left;">-0.606***</td>
</tr>
<tr class="even">
<td style="text-align: left;">Clay</td>
<td style="text-align: left;">-0.006***</td>
<td style="text-align: left;">-0.016***</td>
<td style="text-align: left;">-0.085***</td>
<td style="text-align: left;">0.015</td>
<td style="text-align: left;">-0.029***</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(C_{org}\)</span></td>
<td style="text-align: left;">0.612</td>
<td style="text-align: left;">0.137</td>
<td style="text-align: left;">1.250</td>
<td style="text-align: left;">0.269</td>
<td style="text-align: left;">1.454</td>
</tr>
<tr class="even">
<td style="text-align: left;">pH</td>
<td style="text-align: left;">-0.018***</td>
<td style="text-align: left;">-0.021***</td>
<td style="text-align: left;">-0.092***</td>
<td style="text-align: left;">0.124</td>
<td style="text-align: left;">0.012</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Silt</td>
<td style="text-align: left;">-0.000***</td>
<td style="text-align: left;">0.004</td>
<td style="text-align: left;">0.008</td>
<td style="text-align: left;">-0.015***</td>
<td style="text-align: left;">-0.049***</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(R^2_m\)</span></td>
<td style="text-align: left;">0.393</td>
<td style="text-align: left;">0.212</td>
<td style="text-align: left;">0.368</td>
<td style="text-align: left;">0.362</td>
<td style="text-align: left;">0.494</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(R^2_c\)</span></td>
<td style="text-align: left;">0.996</td>
<td style="text-align: left;">0.915</td>
<td style="text-align: left;">0.993</td>
<td style="text-align: left;">0.995</td>
<td style="text-align: left;">0.997</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The analysis reveals that the capacity-based P pools and the kinetic rate constant are controlled by different sets of soil properties, strongly supporting the hypotheses.</p>
<p>In line with <strong>Hypothesis 2b</strong>, the kinetic capacity parameter, <strong>Desorbable P (</strong><span class="math inline">\(P_{desorb}\)</span>), showed a highly significant negative relationship with both dithionite-extractable iron (<span class="math inline">\(Fe_d\)</span>) and aluminum (<span class="math inline">\(Al_d\)</span>). This provides strong evidence that the total pool of free oxides, which represent the primary P sorption surfaces in the soil, is a key factor controlling the size of the readily desorbable P pool.</p>
<p>Also confirming <strong>Hypothesis 2b</strong>, the <strong>Rate Constant (<em>k</em>)</strong> was governed by a different set of properties. It was not significantly influenced by the free oxides but instead showed a significant negative relationship with <code>Clay</code> content and a positive relationship with organic carbon (<span class="math inline">\(C_{org}\)</span>). This clearly distinguishes the kinetic component from the capacity component, suggesting that while oxides control <em>how much</em> P can be held, soil texture and organic matter influence <em>how fast</em> it can be released.</p>
<p>The standard STP methods showed patterns consistent with <strong>Hypothesis 1b</strong>. <strong>Organic Carbon (</strong><span class="math inline">\(C_{org}\)</span>) had a highly significant positive effect on <span class="math inline">\(P_{AAE10}\)</span>, and <strong>pH</strong> had a significant negative effect, as predicted. The relationship of the STP measures with the dithionite-extractable oxides was less consistent than that of <span class="math inline">\(P_{desorb}\)</span>, with only <span class="math inline">\(P_{AAE10}\)</span> showing a significant negative link to <span class="math inline">\(Al_d\)</span>.</p>
</section>
<section id="sec-agronomic-modeling" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="sec-agronomic-modeling"><span class="header-section-number">1.5</span> Predictive Modeling of Agronomic Outcomes</h2>
<p>To formally evaluate the predictive power of the standard STP methods against the kinetic parameters, a series of linear mixed-effects models were fitted for each of the primary agronomic response variables. To test the central hypotheses of this thesis, the predictive power of the kinetic parameters was directly compared against that of the standard STP methods for several key agronomic outcomes. For each response variable—Normalized Yield (<span class="math inline">\(Y_{rel}\)</span>), P Uptake (<span class="math inline">\(P_{up}\)</span>), and P Balance (<span class="math inline">\(P_{bal}\)</span>)—a set of competing linear mixed-effects models was constructed.</p>
<p>To ensure a fair comparison, all models shared an identical random effects structure (<code>(1|year) + (1|Site) + (1|Site:block)</code>), differing only in their fixed effects. Four distinct models were evaluated: <span class="math inline">\(P_{CO_2}\)</span> Model: Used the standard water-soluble P test as the sole predictor. <span class="math inline">\(P_{AAE10}\)</span> Model: Used the standard chelate-extractable P test as the sole predictor. <strong>STP Interaction Model:</strong> Included both standard tests and their interaction term (<span class="math inline">\(P_{CO_2} * P_{AAE10}\)</span>) to capture their combined effect. <strong>Kinetic Model:</strong> Used the log-transformed desorbable P pool (<span class="math inline">\(log(P_{desorb})\)</span>), the rate constant (<em>k</em>), and their interaction (<span class="math inline">\(J_0\)</span>) as predictors.</p>
<p>The performance of these models for each agronomic outcome is presented in the following sections.</p>
<section id="anomaly-in-the-cadenazzo-yield-data" class="level3" data-number="1.5.1">
<h3 data-number="1.5.1" class="anchored" data-anchor-id="anomaly-in-the-cadenazzo-yield-data"><span class="header-section-number">1.5.1</span> Anomaly in the Cadenazzo Yield Data</h3>
<p>A preliminary visual analysis of the agronomic data revealed a significant anomaly at the Cadenazzo (CAD) site. As shown in <a href="#fig-yield-comparison" class="quarto-xref">Figure&nbsp;6</a>, the Cadenazzo site exhibited substantially higher overall yields than all other locations. More critically, the yield response to P fertilization did not follow the expected agronomic trend. The zero-fertilizer treatment (<code>P0</code>) showed the highest median yield, while the surplus treatment (<code>P166</code>) was among the lowest.</p>
<p>A simple label swap between <code>P0</code> and <code>P166</code> was hypothesized and tested (<a href="#fig-yield-cadenazzo-fix" class="quarto-xref">Figure&nbsp;7</a>). While this correction established a more monotonic trend, the resulting pattern remained questionable, with the corrected <code>P166</code> yield being inexplicably higher than the <code>P100</code> and <code>P133</code> treatments, which is not a typical biological response.</p>
<p>Unfortunately, a deeper investigation into the cause of this anomaly was impossible, as the corresponding soil analysis data (STPs, organic carbon, etc.) for the Cadenazzo site were unavailable due to sample loss. Without this data, it cannot be determined whether the issue stems from a persistent micro-site anomaly, a more complex data recording error, or other unknown factors. Given these unresolved inconsistencies and the site’s unusually high productivity, the Cadenazzo data was retained in the models but is recognized as a significant source of unexplained variance that likely contributed to the poor predictive performance of all models for yield-related metrics like <span class="math inline">\(Y_{norm}\)</span> and <span class="math inline">\(Y_{rel}\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-yield-comparison" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-yield-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="25-results_files/figure-html/fig-yield-comparison-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-yield-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Annual dry matter yield across P fertilization treatments, faceted by experimental site, highlighting the anomalous pattern at Cadenazzo (CAD).
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-yield-cadenazzo-fix" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-yield-cadenazzo-fix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="25-results_files/figure-html/fig-yield-cadenazzo-fix-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-yield-cadenazzo-fix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Comparison of Cadenazzo yields with original and swapped (P0 &lt;&gt; P166) treatment labels.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="predicting-site-normalized-yield-y_norm" class="level3" data-number="1.5.2">
<h3 data-number="1.5.2" class="anchored" data-anchor-id="predicting-site-normalized-yield-y_norm"><span class="header-section-number">1.5.2</span> Predicting Site-Normalized Yield (<span class="math inline">\(Y_{norm}\)</span>)</h3>
<p>The analysis reveals a clear and striking difference between the predictive power of the standard STP methods and the kinetic parameters for site-normalized yield, as seen in <a href="#tbl-ynorm-models" class="quarto-xref">Table&nbsp;2</a>.</p>
<div class="cell">
<div id="tbl-ynorm-models" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ynorm-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Results of linear mixed-effects models predicting Site-Normalized Yield (<span class="math inline">\(Y_{norm}\)</span>).
</figcaption>
<div aria-describedby="tbl-ynorm-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 37%">
<col style="width: 14%">
<col style="width: 16%">
<col style="width: 21%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Predictor</th>
<th style="text-align: left;"><span class="math inline">\(P_{CO_2}\)</span></th>
<th style="text-align: left;"><span class="math inline">\(P_{AAE10}\)</span></th>
<th style="text-align: left;">STP-interaction</th>
<th style="text-align: left;">kinetic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: left;">1.059***</td>
<td style="text-align: left;">0.532***</td>
<td style="text-align: left;">1.096***</td>
<td style="text-align: left;">0.980</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(k\)</span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">2.262</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(J_0\)</span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">0.931</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(P_{desorb}\)</span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">-0.063</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(P_{AAE10}\)</span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">0.120***</td>
<td style="text-align: left;">-0.006</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(P_{CO_2}\)</span></td>
<td style="text-align: left;">0.162***</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">0.137</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(P_{CO_2} \times P_{AAE10}\)</span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">0.016</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(R^2_m\)</span></td>
<td style="text-align: left;">0.218</td>
<td style="text-align: left;">0.198</td>
<td style="text-align: left;">0.220</td>
<td style="text-align: left;">0.014</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(R^2_c\)</span></td>
<td style="text-align: left;">0.358</td>
<td style="text-align: left;">0.474</td>
<td style="text-align: left;">0.365</td>
<td style="text-align: left;">0.360</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The analysis for site-normalized yield showed that both the <code>$P_{CO_2}$</code> and <code>$P_{AAE10}$</code> models had highly significant coefficients and explained 21.8% and 19.8% of the variance, respectively. The combined STP-interaction model performed best, explaining 22% of the variance. In contrast, the kinetic model had a marginal R² of only 1.4%, and none of its parameters were statistically significant.</p>
</section>
<section id="predicting-national-normalized-yield-y_rel" class="level3" data-number="1.5.3">
<h3 data-number="1.5.3" class="anchored" data-anchor-id="predicting-national-normalized-yield-y_rel"><span class="header-section-number">1.5.3</span> Predicting National-Normalized Yield (<span class="math inline">\(Y_{rel}\)</span>)</h3>
<p>The models predicting national-normalized yield (<span class="math inline">\(Y_{rel}\)</span>) reveal that both standard and kinetic soil phosphorus tests struggle to explain the variance in crop yields on their own, though standard tests show slightly better performance in this context.</p>
<div class="cell">
<div id="tbl-yrel-models" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-yrel-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Results of linear mixed-effects models predicting National-Normalized Yield (<span class="math inline">\(Y_{rel}\)</span>).
</figcaption>
<div aria-describedby="tbl-yrel-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 36%">
<col style="width: 14%">
<col style="width: 15%">
<col style="width: 20%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Predictor</th>
<th style="text-align: left;"><span class="math inline">\(P_{CO_2}\)</span></th>
<th style="text-align: left;"><span class="math inline">\(P_{AAE10}\)</span></th>
<th style="text-align: left;">STP-interaction</th>
<th style="text-align: left;">kinetic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: left;">104.862***</td>
<td style="text-align: left;">75.343***</td>
<td style="text-align: left;">130.274***</td>
<td style="text-align: left;">56.375</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(k\)</span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">377.498**</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(J_0\)</span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">171.507**</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(P_{desorb}\)</span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">-27.486*</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(P_{AAE10}\)</span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">7.111**</td>
<td style="text-align: left;">-6.537</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(P_{CO_2}\)</span></td>
<td style="text-align: left;">8.853**</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">23.091</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(P_{CO_2} \times P_{AAE10}\)</span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">-3.110</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(R^2_m\)</span></td>
<td style="text-align: left;">0.074</td>
<td style="text-align: left;">0.063</td>
<td style="text-align: left;">0.078</td>
<td style="text-align: left;">0.022</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(R^2_c\)</span></td>
<td style="text-align: left;">0.569</td>
<td style="text-align: left;">0.537</td>
<td style="text-align: left;">0.596</td>
<td style="text-align: left;">0.439</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<section id="performance-of-standard-stp-methods" class="level4" data-number="1.5.3.1">
<h4 data-number="1.5.3.1" class="anchored" data-anchor-id="performance-of-standard-stp-methods"><span class="header-section-number">1.5.3.1</span> Performance of Standard STP Methods</h4>
<p>The models based on standard soil tests, <code>$P_{CO_2}$</code> and <code>$P_{AAE10}$</code>, were significant predictors, explaining 7.4% and 6.3% of the variance in yield, respectively. The model including their interaction term performed slightly better, explaining 7.8% of the variance. The model based on kinetic parameters demonstrated lower predictive power, with a marginal R² of 2.2%. A critical observation across all models is the large discrepancy between the marginal R² (<span class="math inline">\(R^2_m\)</span>) and the conditional R² (<span class="math inline">\(R^2_c\)</span>). For instance, in the best-performing STP model, the marginal R² is only 0.078, but the conditional R² is 0.596.</p>
</section>
</section>
<section id="predicting-p-uptake-p_up" class="level3" data-number="1.5.4">
<h3 data-number="1.5.4" class="anchored" data-anchor-id="predicting-p-uptake-p_up"><span class="header-section-number">1.5.4</span> Predicting P-Uptake (<span class="math inline">\(P_{up}\)</span>)</h3>
<p>When predicting P-uptake, both the standard and kinetic models demonstrate similarly weak predictive power, with none of the approaches standing out as superior.</p>
<div class="cell">
<div id="tbl-pexport-models" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pexport-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Results of linear mixed-effects models predicting P-Export (<span class="math inline">\(P_{up}\)</span>).
</figcaption>
<div aria-describedby="tbl-pexport-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 36%">
<col style="width: 14%">
<col style="width: 15%">
<col style="width: 20%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Predictor</th>
<th style="text-align: left;"><span class="math inline">\(P_{CO_2}\)</span></th>
<th style="text-align: left;"><span class="math inline">\(P_{AAE10}\)</span></th>
<th style="text-align: left;">STP-interaction</th>
<th style="text-align: left;">kinetic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: left;">27.522***</td>
<td style="text-align: left;">8.090</td>
<td style="text-align: left;">30.632*</td>
<td style="text-align: left;">29.599***</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(k\)</span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">22.622</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(J_0\)</span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">11.928</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(P_{desorb}\)</span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">1.954</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(P_{AAE10}\)</span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">4.824***</td>
<td style="text-align: left;">-0.805</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(P_{CO_2}\)</span></td>
<td style="text-align: left;">5.177***</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">8.069</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(P_{CO_2} \times P_{AAE10}\)</span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">-0.814</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(R^2_m\)</span></td>
<td style="text-align: left;">0.064</td>
<td style="text-align: left;">0.073</td>
<td style="text-align: left;">0.065</td>
<td style="text-align: left;">0.064</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(R^2_c\)</span></td>
<td style="text-align: left;">0.625</td>
<td style="text-align: left;">0.603</td>
<td style="text-align: left;">0.623</td>
<td style="text-align: left;">0.648</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>When predicting P-uptake, the individual standard soil tests, <span class="math inline">\(P_{CO_2}\)</span> and <span class="math inline">\(P_{AAE10}\)</span>, were significant positive predictors, explaining 6.4% and 7.3% of the variance, respectively. The interaction model did not improve the explained variance. The kinetic model performed on par with the standard individual tests, explaining 6.4% of the variance, though none of its parameters were individually significant. As with yield, a large difference between the marginal and conditional R² values was observed across all models.</p>
</section>
<section id="predicting-p-balance-p_bal" class="level3" data-number="1.5.5">
<h3 data-number="1.5.5" class="anchored" data-anchor-id="predicting-p-balance-p_bal"><span class="header-section-number">1.5.5</span> Predicting P-Balance (<span class="math inline">\(P_{bal}\)</span>)</h3>
<p>The prediction of the P-Balance (<span class="math inline">\(P_{bal}\)</span>) reveals a stark and decisive contrast between the kinetic and standard STP approaches, providing the strongest evidence in favor of the kinetic methodology.</p>
<div class="cell">
<div id="tbl-pbalance-models" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pbalance-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Results of linear mixed-effects models predicting P-Balance (<span class="math inline">\(P_{bal}\)</span>).
</figcaption>
<div aria-describedby="tbl-pbalance-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 36%">
<col style="width: 14%">
<col style="width: 15%">
<col style="width: 20%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Predictor</th>
<th style="text-align: left;"><span class="math inline">\(P_{CO_2}\)</span></th>
<th style="text-align: left;"><span class="math inline">\(P_{AAE10}\)</span></th>
<th style="text-align: left;">STP-interaction</th>
<th style="text-align: left;">kinetic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: left;">4.441</td>
<td style="text-align: left;">7.691</td>
<td style="text-align: left;">3.649</td>
<td style="text-align: left;">43.833***</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(k\)</span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">84.993</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(J_0\)</span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">33.029</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(P_{desorb}\)</span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">16.947***</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(P_{AAE10}\)</span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">-0.794</td>
<td style="text-align: left;">0.187</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(P_{CO_2}\)</span></td>
<td style="text-align: left;">-0.928</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">-2.442</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(P_{CO_2} \times P_{AAE10}\)</span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">0.462</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(R^2_m\)</span></td>
<td style="text-align: left;">0.001</td>
<td style="text-align: left;">0.001</td>
<td style="text-align: left;">0.001</td>
<td style="text-align: left;">0.572</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(R^2_c\)</span></td>
<td style="text-align: left;">0.810</td>
<td style="text-align: left;">0.807</td>
<td style="text-align: left;">0.811</td>
<td style="text-align: left;">0.744</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The kinetic model emerged as a strong predictor of the P-Balance, explaining 57.2% of the variance, with the desorbable P pool (<span class="math inline">\(P_{desorb}\)</span>) being a highly significant predictor. In contrast, all models based on the standard STP methods had marginal R² values of 0.1% and no significant predictors. The conditional R² for the STP models was high (around 0.81), while the kinetic model had both a high marginal R² (0.572) and a high conditional R² (0.744).</p>



</section>
</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-demariaSoilPropertiesPhosphorus2013" class="csl-entry" role="listitem">
Demaria, P., Sinaj, S., Flisch, R., &amp; Frossard, E. (2013). Soil <span>Properties</span> and <span>Phosphorus Isotopic Exchangeability</span> in <span>Cropped Temperate Soils</span>. <em>Communications in Soil Science and Plant Analysis</em>, <em>44</em>(1–4), 287–300. <a href="https://doi.org/10.1080/00103624.2013.741896">https://doi.org/10.1080/00103624.2013.741896</a>
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ptochosgeorgos\.github\.io\/Article-P-desorption-kinetics\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>