<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Marc Jerónimo Pérez y Ropero">
<meta name="author" content="Frank Liebisch">
<meta name="dcterms.date" content="2026-09-18">
<meta name="keywords" content="Phosphorus Desorption, Soil Test Phosphorus (STP), Bayesian Mixed Models, Crop Yield Predictability, STYCS">

<title>P-release kinetics as a predictor for P-availability in Swiss cropping systems – STYCS P-Kinetics Manuscript</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-04f38dd05d8273ce930b2d623817583d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">STYCS P-Kinetics Manuscript</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">Manuscript</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-supplementary-models" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Supplementary Models</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-supplementary-models">    
        <li>
    <a class="dropdown-item" href="./notebooks/qi_modelling1.html">
 <span class="dropdown-text">Q/I &amp; Thermodynamic Showdown</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./notebooks/qi_modelling_parallel.html">
 <span class="dropdown-text">Digital Annex: Q/I Modeling of P Kinetics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./notebooks/bayesian_modelling.html">
 <span class="dropdown-text">Bayesian Yield &amp; Uptake Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./notebooks/sanity_checks.html">
 <span class="dropdown-text">Data Sanity Checks</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./presentation/index.html"> 
<span class="menu-text">Presentation (Main)</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./presentation_grud/index.html"> 
<span class="menu-text">Presentation (GRUD)</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#the-agronomic-dilemma-of-phosphorus" id="toc-the-agronomic-dilemma-of-phosphorus" class="nav-link" data-scroll-target="#the-agronomic-dilemma-of-phosphorus"><span class="header-section-number">1.1</span> The Agronomic Dilemma of Phosphorus</a></li>
  <li><a href="#conceptual-frameworks-vs.-operational-definitions" id="toc-conceptual-frameworks-vs.-operational-definitions" class="nav-link" data-scroll-target="#conceptual-frameworks-vs.-operational-definitions"><span class="header-section-number">1.2</span> Conceptual Frameworks vs.&nbsp;Operational Definitions</a></li>
  <li><a href="#the-asymmetry-of-measurement-thermodynamics-vs.-biology" id="toc-the-asymmetry-of-measurement-thermodynamics-vs.-biology" class="nav-link" data-scroll-target="#the-asymmetry-of-measurement-thermodynamics-vs.-biology"><span class="header-section-number">1.3</span> The Asymmetry of Measurement: Thermodynamics vs.&nbsp;Biology</a></li>
  <li><a href="#grounding-agronomy-in-thermodynamic-principles" id="toc-grounding-agronomy-in-thermodynamic-principles" class="nav-link" data-scroll-target="#grounding-agronomy-in-thermodynamic-principles"><span class="header-section-number">1.4</span> Grounding Agronomy in Thermodynamic Principles</a></li>
  <li><a href="#unifying-quantity-intensity-and-the-kinetic-bottleneck" id="toc-unifying-quantity-intensity-and-the-kinetic-bottleneck" class="nav-link" data-scroll-target="#unifying-quantity-intensity-and-the-kinetic-bottleneck"><span class="header-section-number">1.5</span> Unifying Quantity, Intensity, and the Kinetic Bottleneck</a></li>
  <li><a href="#thesis-objectives-and-analytical-strategy" id="toc-thesis-objectives-and-analytical-strategy" class="nav-link" data-scroll-target="#thesis-objectives-and-analytical-strategy"><span class="header-section-number">1.6</span> Thesis Objectives and Analytical Strategy</a></li>
  </ul></li>
  <li><a href="#sec-materials-and-methods" id="toc-sec-materials-and-methods" class="nav-link" data-scroll-target="#sec-materials-and-methods"><span class="header-section-number">2</span> Materials and Methods</a>
  <ul class="collapse">
  <li><a href="#sec-the-long-term-phosphorus-fertilization-experiment" id="toc-sec-the-long-term-phosphorus-fertilization-experiment" class="nav-link" data-scroll-target="#sec-the-long-term-phosphorus-fertilization-experiment"><span class="header-section-number">2.1</span> The Long-Term Phosphorus Fertilization Experiment</a>
  <ul class="collapse">
  <li><a href="#crop-yield-phosphorus-uptake-and-balances" id="toc-crop-yield-phosphorus-uptake-and-balances" class="nav-link" data-scroll-target="#crop-yield-phosphorus-uptake-and-balances"><span class="header-section-number">2.1.1</span> Crop Yield, Phosphorus Uptake, and Balances</a></li>
  </ul></li>
  <li><a href="#analytical-workflow-and-data-integration" id="toc-analytical-workflow-and-data-integration" class="nav-link" data-scroll-target="#analytical-workflow-and-data-integration"><span class="header-section-number">2.2</span> Analytical Workflow and Data Integration</a></li>
  <li><a href="#sec-experimental-sites" id="toc-sec-experimental-sites" class="nav-link" data-scroll-target="#sec-experimental-sites"><span class="header-section-number">2.3</span> Experimental Sites</a></li>
  <li><a href="#sec-phosphorus-desorption-kinetics" id="toc-sec-phosphorus-desorption-kinetics" class="nav-link" data-scroll-target="#sec-phosphorus-desorption-kinetics"><span class="header-section-number">2.4</span> Phosphorus Desorption Kinetics and Thermodynamics</a>
  <ul class="collapse">
  <li><a href="#sec-adapted-kinetic-protocol-for-this-study" id="toc-sec-adapted-kinetic-protocol-for-this-study" class="nav-link" data-scroll-target="#sec-adapted-kinetic-protocol-for-this-study"><span class="header-section-number">2.4.1</span> Adapted Kinetic Protocol for This Study</a></li>
  <li><a href="#temporal-stability-of-amorphous-metal-oxides" id="toc-temporal-stability-of-amorphous-metal-oxides" class="nav-link" data-scroll-target="#temporal-stability-of-amorphous-metal-oxides"><span class="header-section-number">2.4.2</span> Temporal Stability of Amorphous Metal Oxides</a></li>
  </ul></li>
  <li><a href="#sec-statistical-analysis" id="toc-sec-statistical-analysis" class="nav-link" data-scroll-target="#sec-statistical-analysis"><span class="header-section-number">2.5</span> Statistical Analysis and Modeling</a>
  <ul class="collapse">
  <li><a href="#modeling-of-desorption-kinetics-and-the-desorption-velocity-v_0" id="toc-modeling-of-desorption-kinetics-and-the-desorption-velocity-v_0" class="nav-link" data-scroll-target="#modeling-of-desorption-kinetics-and-the-desorption-velocity-v_0"><span class="header-section-number">2.5.1</span> 1. Modeling of Desorption Kinetics and the Desorption Velocity (<span class="math inline">\(v_0\)</span>)</a></li>
  <li><a href="#thermodynamic-qi-isotherms-and-buffering-capacity" id="toc-thermodynamic-qi-isotherms-and-buffering-capacity" class="nav-link" data-scroll-target="#thermodynamic-qi-isotherms-and-buffering-capacity"><span class="header-section-number">2.5.2</span> 2. Thermodynamic <span class="math inline">\(Q(I)\)</span> Isotherms and Buffering Capacity</a></li>
  <li><a href="#agronomic-normalization-controlling-pedoclimatic-noise" id="toc-agronomic-normalization-controlling-pedoclimatic-noise" class="nav-link" data-scroll-target="#agronomic-normalization-controlling-pedoclimatic-noise"><span class="header-section-number">2.5.3</span> 3. Agronomic Normalization: Controlling Pedoclimatic Noise</a></li>
  <li><a href="#bayesian-modeling-of-agronomic-outcomes" id="toc-bayesian-modeling-of-agronomic-outcomes" class="nav-link" data-scroll-target="#bayesian-modeling-of-agronomic-outcomes"><span class="header-section-number">2.5.4</span> 4. Bayesian Modeling of Agronomic Outcomes</a></li>
  <li><a href="#the-bayesian-fragility-of-the-mitscherlich-equation" id="toc-the-bayesian-fragility-of-the-mitscherlich-equation" class="nav-link" data-scroll-target="#the-bayesian-fragility-of-the-mitscherlich-equation"><span class="header-section-number">2.5.5</span> The Bayesian Fragility of the Mitscherlich Equation</a></li>
  <li><a href="#mechanistic-modeling-of-the-rhizosphere-barber-cushman-modification" id="toc-mechanistic-modeling-of-the-rhizosphere-barber-cushman-modification" class="nav-link" data-scroll-target="#mechanistic-modeling-of-the-rhizosphere-barber-cushman-modification"><span class="header-section-number">2.5.6</span> 5. Mechanistic Modeling of the Rhizosphere (Barber-Cushman Modification)</a></li>
  <li><a href="#derivation-of-critical-thresholds-p_textcrit" id="toc-derivation-of-critical-thresholds-p_textcrit" class="nav-link" data-scroll-target="#derivation-of-critical-thresholds-p_textcrit"><span class="header-section-number">2.5.7</span> 6. Derivation of Critical Thresholds (<span class="math inline">\(P_{\text{crit}}\)</span>)</a></li>
  <li><a href="#the-management-of-covariate-data-two-distinct-approaches" id="toc-the-management-of-covariate-data-two-distinct-approaches" class="nav-link" data-scroll-target="#the-management-of-covariate-data-two-distinct-approaches"><span class="header-section-number">2.5.8</span> 7. The Management of Covariate Data: Two Distinct Approaches</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">3</span> Results</a>
  <ul class="collapse">
  <li><a href="#the-blind-spot-of-empirical-soil-tests" id="toc-the-blind-spot-of-empirical-soil-tests" class="nav-link" data-scroll-target="#the-blind-spot-of-empirical-soil-tests"><span class="header-section-number">3.1</span> The Blind Spot of Empirical Soil Tests</a></li>
  <li><a href="#plant-response-variables" id="toc-plant-response-variables" class="nav-link" data-scroll-target="#plant-response-variables"><span class="header-section-number">3.2</span> Plant Response Variables</a></li>
  <li><a href="#yield-model-comparison" id="toc-yield-model-comparison" class="nav-link" data-scroll-target="#yield-model-comparison"><span class="header-section-number">3.3</span> Yield model comparison</a></li>
  <li><a href="#phosphorus-uptake-c_p-model-comparison" id="toc-phosphorus-uptake-c_p-model-comparison" class="nav-link" data-scroll-target="#phosphorus-uptake-c_p-model-comparison"><span class="header-section-number">3.4</span> Phosphorus Uptake (<span class="math inline">\(C_P\)</span>) model comparison</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">4</span> Discussion</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">5</span> Conclusion</a></li>
  <li><a href="#acknowledgments" id="toc-acknowledgments" class="nav-link" data-scroll-target="#acknowledgments"><span class="header-section-number">6</span> Acknowledgments</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">7</span> References</a></li>
  <li><a href="#appendix-thermodynamic-correction-of-p_-extco_2-extractions" id="toc-appendix-thermodynamic-correction-of-p_-extco_2-extractions" class="nav-link" data-scroll-target="#appendix-thermodynamic-correction-of-p_-extco_2-extractions"><span class="header-section-number">8</span> Appendix: Thermodynamic Correction of <span class="math inline">\(P_{    ext{CO}_2}\)</span> Extractions</a>
  <ul class="collapse">
  <li><a href="#a.1.-intrinsic-ionic-strength-of-the-p_-extco_2-extractant" id="toc-a.1.-intrinsic-ionic-strength-of-the-p_-extco_2-extractant" class="nav-link" data-scroll-target="#a.1.-intrinsic-ionic-strength-of-the-p_-extco_2-extractant"><span class="header-section-number">8.1</span> A.1. Intrinsic Ionic Strength of the <span class="math inline">\(P_{    ext{CO}_2}\)</span> Extractant</a></li>
  <li><a href="#a.2.-justification-for-the-davies-equation" id="toc-a.2.-justification-for-the-davies-equation" class="nav-link" data-scroll-target="#a.2.-justification-for-the-davies-equation"><span class="header-section-number">8.2</span> A.2. Justification for the Davies Equation</a></li>
  <li><a href="#a.3.-implementation-of-thermodynamic-correction" id="toc-a.3.-implementation-of-thermodynamic-correction" class="nav-link" data-scroll-target="#a.3.-implementation-of-thermodynamic-correction"><span class="header-section-number">8.3</span> A.3. Implementation of Thermodynamic Correction</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li><li><a href="index.pdf"><i class="bi bi-file-pdf"></i>PDF (elsevier)</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">P-release kinetics as a predictor for P-availability in Swiss cropping systems</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Marc Jerónimo Pérez y Ropero <a href="mailto:marc.perez@agroscope.admin.ch" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Agroscope Reckenholz
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Frank Liebisch </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Agroscope Reckenholz
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 18, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>Current empirical Soil Test Phosphorus (STP) methods (<span class="math inline">\(P_{CO_2}\)</span>, <span class="math inline">\(P_{AAE10}\)</span>) use static pools and arbitrary supply classes that ignore the physics of how soils release P over time. In this study, we evaluate… [Insert full abstract here]</p>
  </div>
</div>

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>Phosphorus Desorption, Soil Test Phosphorus (STP), Bayesian Mixed Models, Crop Yield Predictability, STYCS</p>
  </div>
</div>

</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<section id="the-agronomic-dilemma-of-phosphorus" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="the-agronomic-dilemma-of-phosphorus"><span class="header-section-number">1.1</span> The Agronomic Dilemma of Phosphorus</h2>
<p>Phosphorus (P) is an essential macronutrient for all life, yet its management in agricultural systems presents a significant challenge. In the soil solution, P exists predominantly as highly reactive orthophosphate anions (<span class="math inline">\(HPO_4^{2-}\)</span> or <span class="math inline">\(H_2PO_4^{-}\)</span>). These dissolved species are rapidly immobilized—either adsorbed onto the surfaces of clays and metal oxides or precipitated with cations like calcium, iron, and aluminum to form minerals of low solubility <span class="citation" data-cites="Brady2016Soils Sposito2008Chemistry">(<a href="#ref-Brady2016Soils" role="doc-biblioref">Brady &amp; Weil, 2016</a>; <a href="#ref-Sposito2008Chemistry" role="doc-biblioref">Sposito, 2008</a>)</span>. Consequently, the total soil P stock is vast, but the minute fraction dissolved in the soil solution—the only form directly available to plant roots—is highly transient.</p>
<p>To manage this complex nutrient, European agricultural systems rely heavily on empirical soil tests to generate fertilizer recommendations. As detailed by <span class="citation" data-cites="jordan-meilleOverviewFertilizerPRecommendations2012">Jordan-Meille et al. (<a href="#ref-jordan-meilleOverviewFertilizerPRecommendations2012" role="doc-biblioref">2012</a>)</span> and later expanded by <span class="citation" data-cites="steinfurthThresholdsTargetPhosphorus2022"><span class="nocase">Steinfurth et al.</span> (<a href="#ref-steinfurthThresholdsTargetPhosphorus2022" role="doc-biblioref">2022</a>)</span>, these systems generally follow a three-step procedure: soil testing, calibration, and recommendation. Central to this process is the “Class Concept” (Klassenkonzept), where raw soil test values are calibrated into discrete P-fertility categories (e.g., Very Low, Target, Excessive). In many European countries, including Switzerland and France, these empirical thresholds are further modified by secondary soil parameters such as clay content and pH.</p>
<p>However, despite these sophisticated calibration matrices, inter-laboratory comparisons reveal massive contradictions, with recommended fertilizer doses for the exact same soil varying by up to 300% across Europe <span class="citation" data-cites="jordan-meilleOverviewFertilizerPRecommendations2012">(<a href="#ref-jordan-meilleOverviewFertilizerPRecommendations2012" role="doc-biblioref">Jordan-Meille et al., 2012</a>)</span>. This fundamental instability arises because standard chemical extractants largely ignore the mechanistic processes governing plant P uptake.</p>
</section>
<section id="conceptual-frameworks-vs.-operational-definitions" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="conceptual-frameworks-vs.-operational-definitions"><span class="header-section-number">1.2</span> Conceptual Frameworks vs.&nbsp;Operational Definitions</h2>
<p>To conceptualize plant P availability, soil science relies on three fundamental thermodynamic and mass-balance parameters <span class="citation" data-cites="Frossard2000Processes">(<a href="#ref-Frossard2000Processes" role="doc-biblioref">Frossard et al., 2000</a>)</span>: 1. <strong>P-Intensity (</strong><span class="math inline">\(I\)</span>): The thermodynamic energy state, or chemical activity, of P in the soil solution at any given moment. 2. <strong>P-Quantity or Capacity (</strong><span class="math inline">\(Q\)</span>): The physical mass of solid-phase P that is readily desorbable and can replenish the soil solution. 3. <strong>Phosphorus Buffering Capacity (PBC):</strong> The resistance of the soil to changes in P-Intensity, mathematically represented as the derivative of Quantity with respect to Intensity (<span class="math inline">\(dQ / dI\)</span>).</p>
<p>While these concepts are theoretically robust, measuring them in natural soils is methodologically challenging. Isotopic Exchange Kinetics (IEK) perfectly capture these dynamics by tracing the true exchangeable pool without altering the chemical equilibrium <span class="citation" data-cites="fardeau1996dynamics galletEffectPhosphateFertilization2003">(<a href="#ref-fardeau1996dynamics" role="doc-biblioref">Fardeau, 1996</a>; <a href="#ref-galletEffectPhosphateFertilization2003" role="doc-biblioref">Gallet et al., 2003</a>)</span>. However, the requirement for radioisotopes renders IEK unsuitable for routine agronomic testing. In practice, standard agronomic soil tests do not measure absolute thermodynamic states; rather, they rely on <strong>operational definitions</strong> that often misrepresent the true pool of available P <span class="citation" data-cites="demariaExchangeabilityPhosphateExtracted2005">(<a href="#ref-demariaExchangeabilityPhosphateExtracted2005" role="doc-biblioref">Demaria et al., 2005</a>)</span>. A soil test value is strictly defined by the specific chemical extractant used, the extraction time, and the soil-to-solution ratio.</p>
<p>Different standard methods target different physicochemical pools of P by employing distinct extraction mechanisms: - <strong>Olsen P (</strong><span class="math inline">\(NaHCO_3\)</span>, pH 8.5): Measures desorbable P. The high concentration of bicarbonate ions outcompetes orthophosphate for adsorption sites on soil surfaces <span class="citation" data-cites="Olsen1954">(<a href="#ref-Olsen1954" role="doc-biblioref">Olsen et al., 1954</a>)</span>. - <strong>P-AAE10 (Ammonium Acetate EDTA, pH 4.65):</strong> A strong extractant that attacks both sorbed and precipitated P forms. EDTA chelates background cations, actively dissolving apatites, while the acetate buffer facilitates desorption <span class="citation" data-cites="FAL1996Methodenbuch">(<a href="#ref-FAL1996Methodenbuch" role="doc-biblioref">Forschungsanstalt für Agrarökologie und Landbau (FAL), 1996</a>)</span>. - <strong>Water Extractions (</strong><span class="math inline">\(P_{H_2O}\)</span> and <span class="math inline">\(P_{ ext{CO}_2}\)</span>): While lacking aggressive chelators, distilled or <span class="math inline">\(CO_2\)</span>-saturated water acts as an incredibly strong thermodynamic sink. By plunging the soil into a massively dilute environment, it forcefully drives dissolution and desorption to re-establish equilibrium. Consequently, the actual extracting power of these methods is fiercely modulated by the physical extraction time and, crucially, the soil-to-extractant ratio.</p>
</section>
<section id="the-asymmetry-of-measurement-thermodynamics-vs.-biology" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="the-asymmetry-of-measurement-thermodynamics-vs.-biology"><span class="header-section-number">1.3</span> The Asymmetry of Measurement: Thermodynamics vs.&nbsp;Biology</h2>
<p>Relying on operational definitions introduces severe analytical limitations, but a profound epistemological asymmetry exists between the chemical measurements of the soil and the biological measurements of the plant.</p>
<p>On the soil side, thermodynamic measurements can be mechanistically clarified. While empirical tests like <span class="math inline">\(P_{AAE10}\)</span> suffer from clear artifacts (such as the physical saturation of the EDTA chelator in heavy clays), we can rationally address these limitations. We can convert stoichiometric concentrations to corrected chemical activities (<span class="math inline">\(\gamma\)</span>) using Davies or Pitzer equations, isolate kinetic bottlenecks, and model fundamental isotherms. We have rational, physical control over the soil matrix.</p>
<p>Conversely, biological response variables are inherently messy, abstract, and riddled with physiological ambiguity. Agronomic models attempt to use plant tissue concentrations (<span class="math inline">\(C_P\)</span>) or total Phosphorus Uptake (<span class="math inline">\(P_{    ext{up}}\)</span>) as response variables, but these are not absolute physical truths. They are abstractions derived from indirect measurements of mass and concentration.</p>
<p>Furthermore, these biological metrics routinely collapse in the field due to physiological phenomena like the <strong>Piper-Steenbjerg effect</strong> (carbon dilution) <span class="citation" data-cites="hirteYieldResponseSoil2021">(<a href="#ref-hirteYieldResponseSoil2021" role="doc-biblioref">Hirte et al., 2021</a>)</span>. When a severely P-starved plant finally receives Phosphorus, it rapidly generates new biomass. This burst of growth paradoxically <em>dilutes</em> the tissue <span class="math inline">\(C_P\)</span> concentration, causing the measured concentration to drop even though the total Phosphorus mass in the plant increased. This immediately forces an arbitrary decision: which specific plant tissue should we optimize to represent the whole organism?</p>
<p>Finally, even if a perfect thermodynamic soil model is constructed, its predictive power in field trials remains constantly threatened by overarching pedoclimatic noise. Much like the Athenians praying to Zeus for rain in the <em>Meditations</em> of Marcus Aurelius, agronomic field trials are ultimately subservient to variables beyond human control. Temperature, precipitation, and soil moisture exert effect estimates that vastly overpower subtle chemical variations. Therefore, while we can mathematically anchor our thermodynamic extractions, predicting biological field outcomes requires accepting a fundamentally chaotic and uncertain reality.</p>
</section>
<section id="grounding-agronomy-in-thermodynamic-principles" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="grounding-agronomy-in-thermodynamic-principles"><span class="header-section-number">1.4</span> Grounding Agronomy in Thermodynamic Principles</h2>
<p>Standard agronomic models frequently rely on empirical curve-fitting, utilizing polynomials or arbitrary linear regressions to maximize <span class="math inline">\(R^2\)</span> values across calibration datasets. While these models may perfectly describe a specific field trial, their parameters are often “dead”—lacking physical meaning and failing spectacularly when extrapolated beyond the calibration environment.</p>
<p>To overcome this, we adopt a more fundamental approach grounded in Thermodynamic Perturbation Theory. By translating empirical extractions into thermodynamic state functions, our models inherit several critical virtues from established physical chemistry frameworks:</p>
<ol type="1">
<li><strong>Method-Agnosticism and Harmonization</strong>: Standard extractions (e.g., Olsen-P at pH 8.5 vs.&nbsp;water extractions at pH ~6) violently alter the chemical equilibrium, making raw extract concentrations across national borders fundamentally incomparable. However, by abstracting these operational extracts into fundamental Quantity (<span class="math inline">\(Q\)</span>) and Intensity (<span class="math inline">\(I\)</span>) metrics—and utilizing models like the Davies or Pitzer equations to isolate true thermodynamic activities—we strip away the artifacts of the extractant’s ionic strength. This thermodynamic translation is the only mathematically rigorous path to harmonizing disparate regional soil tests.</li>
<li><strong>Interpretability via Surface Complexation</strong>: Our parameters are not meaningless regression weights; they are macroscopic reflections of underlying physical phenomena. For example, predicting a kinetic rate constant (<span class="math inline">\(k\)</span>) using the ratio of amorphous aluminum to iron oxides (<span class="math inline">\(Al_{\text{ox}}/Fe_{\text{ox}}\)</span>) directly maps to the distinct electrostatic and lateral repulsion perturbations operating on independent mineral sub-lattices. This mirrors advanced surface complexation frameworks, such as the CD-MUSIC model implemented in Visual MINTEQ by Gustafsson and colleagues <span class="citation" data-cites="gustafssonModelingCompetitiveAnion2001 gustafssonVisualMINTEQ32014">(<a href="#ref-gustafssonModelingCompetitiveAnion2001" role="doc-biblioref">Gustafsson, 2001</a>, <a href="#ref-gustafssonVisualMINTEQ32014" role="doc-biblioref">2014</a>)</span>, which definitively prove that P adsorption non-linearity is governed by spatial charge distribution on specific Fe/Al (hydr)oxide surfaces rather than empirical constants.</li>
<li><strong>Modularity and Expansion</strong>: This approach imports the success of these advanced geochemical models into agronomy. Grounding our agronomic variables in the Gibbs Free Energy expansion provides a rigid mathematical scaffolding that is physically defensible at the thermodynamic boundaries.</li>
</ol>
<p>This theoretical foundation ensures that the model coefficients are physically defensible. Furthermore, it paves the way for advanced statistical updating (e.g., Bayesian inference), allowing future research to introduce meaningful, mechanistic parameterizations rather than blindly chasing variance with higher-order polynomials. We intentionally accept that biological pedoclimatic noise will inevitably lower apparent <span class="math inline">\(R^2\)</span> values in field trials; our objective is structural truth, not mathematical overfitting.</p>
</section>
<section id="unifying-quantity-intensity-and-the-kinetic-bottleneck" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="unifying-quantity-intensity-and-the-kinetic-bottleneck"><span class="header-section-number">1.5</span> Unifying Quantity, Intensity, and the Kinetic Bottleneck</h2>
<p>By pairing an Intensity measurement with a mass extraction (<span class="math inline">\(Q\)</span>, such as <span class="math inline">\(P_{\text{AAE10}}\)</span>), we can construct a generalized <span class="math inline">\(Q(I)\)</span> framework. We parameterize this relationship using a Freundlich isotherm (<span class="math inline">\(Q = K_f \cdot I^{1/n}\)</span>) not because it yields a “true” universal constant, but because its log-log linearization elegantly isolates the baseline capacity (<span class="math inline">\(K_f\)</span>) and the saturation breakdown (<span class="math inline">\(n\)</span>). This thermodynamic abstraction liberates the analysis from the arbitrary, method-specific bounds of operational extractants (e.g., AAE10 vs.&nbsp;CAL vs.&nbsp;Olsen). It translates disparate empirical measurements into a common, transparent language where the Phosphorus Buffering Capacity (PBC) can be derived as the continuous first derivative (<span class="math inline">\(\frac{dQ}{dI}\)</span>) and meaningfully compared across borders.</p>
<p>While the Freundlich model (<span class="math inline">\(Q = K_f \cdot I^{1/n}\)</span>) is mathematically invalid at absolute thermodynamic extremes—failing Henry’s Law near infinite dilution and predicting infinite adsorption rather than a strict saturation limit—it is the correct analytical approximation for operational agricultural soils. Comprehensive heterogeneous models, such as the Langmuir-Freundlich (Sips) or Toth equations, incorporate a saturation denominator (<span class="math inline">\(1 + (aI)^n\)</span>) to enforce a physical maximum. However, agricultural soils operate strictly within the mid-range of the affinity distribution, far below total surface saturation. In this localized “Goldilocks” zone, the saturation term becomes negligible, and the complex Sips and Toth equations collapse mathematically into the classical Freundlich isotherm. Thus, we utilize the Freundlich exponent (<span class="math inline">\(1/n\)</span>) not as a universal law, but as the mathematically exact, localized variance of binding energies across the heterogeneous <span class="math inline">\(Al_{\text{ox}}\)</span> and <span class="math inline">\(Fe_{\text{ox}}\)</span> sub-lattices.</p>
<p>However, even with a correct thermodynamic understanding of <span class="math inline">\(Q\)</span> and <span class="math inline">\(I\)</span>, plant uptake remains fundamentally limited by time. Standard conceptual models assume instantaneous solid-solution equilibrium. In reality, desorption is a rate-limiting kinetic bottleneck <span class="citation" data-cites="Nye2000Solute flossmannExtractionMethodCharacterizing1982">(<a href="#ref-flossmannExtractionMethodCharacterizing1982" role="doc-biblioref">Flossmann &amp; Richter, 1982</a>; <a href="#ref-Nye2000Solute" role="doc-biblioref">Nye &amp; Tinker, 2000</a>)</span>. When a root depletes the rhizosphere, the soil cannot always resupply phosphate fast enough.</p>
<p>To address this, we define a dynamic predictor: the <strong>Initial Activity Flux (</strong><span class="math inline">\(J_0\)</span>). This flux shifts the focus from static mass to supply rate by multiplying the first-order desorption rate constant (<span class="math inline">\(k\)</span>) by the maximum thermodynamic activity (<span class="math inline">\(a_{max}\)</span>): <span class="math display">\[J_0 = k \cdot a_{max}\]</span></p>
<p><a href="#tbl-terminology" class="quarto-xref">Table&nbsp;1</a> maps this transition from classic, operationally defined static tests to the proposed thermodynamic and kinetic parameters.</p>
<div id="tbl-terminology" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-terminology-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Conceptual mapping of fundamental phosphorus availability factors to their analytical proxies.
</figcaption>
<div aria-describedby="tbl-terminology-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Approach / Framework</th>
<th style="text-align: left;">Intensity Factor</th>
<th style="text-align: left;">Quantity (Capacity) Factor</th>
<th style="text-align: left;">Kinetic Factor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Theoretical Concept (<span class="citation" data-cites="Frossard2000Processes">Frossard et al. (<a href="#ref-Frossard2000Processes" role="doc-biblioref">2000</a>)</span>)</strong></td>
<td style="text-align: left;">Concentration of P in the soil solution</td>
<td style="text-align: left;">Pool of solid-phase P that can replenish the solution</td>
<td style="text-align: left;">Rate of P transfer from the solid to the liquid phase</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Traditional / Static Proxy (GRUD)</strong></td>
<td style="text-align: left;"><span class="math inline">\(P_{  ext{CO}_2}\)</span> (Raw Water-soluble Concentration)</td>
<td style="text-align: left;"><span class="math inline">\(P_{AAE10}\)</span> (Chelate-extractable Mass)</td>
<td style="text-align: left;"><em>Not Measured</em></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Dynamic / Kinetic Proxy (This Study)</strong></td>
<td style="text-align: left;">Raw Intensity (<span class="math inline">\(P_{    ext{CO}_2}\)</span>)</td>
<td style="text-align: left;"><span class="math inline">\(P_{AAE10}\)</span></td>
<td style="text-align: left;">Dynamic Desorption Velocity (<span class="math inline">\(v_0 = k \cdot P_{CO_2}\)</span>)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Conceptual model of the rhizosphere phosphorus cycle.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="thesis-objectives-and-analytical-strategy" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="thesis-objectives-and-analytical-strategy"><span class="header-section-number">1.6</span> Thesis Objectives and Analytical Strategy</h2>
<p>This thesis hypothesizes that integrating thermodynamic activity and desorption kinetics provides a more comprehensive mechanistic framework for P-management compared to standard empirical testing. Specifically, it directly answers the call by <span class="citation" data-cites="jordan-meilleOverviewFertilizerPRecommendations2012">Jordan-Meille et al. (<a href="#ref-jordan-meilleOverviewFertilizerPRecommendations2012" role="doc-biblioref">2012</a>)</span> to replace empirical extraction classes with mechanistic sorption-desorption models.</p>
<p>Using soils from the long-term Swiss agricultural experiment STYCS, this study aims to validate this framework through the following core objectives and research questions:</p>
<ol type="1">
<li><strong>Thermodynamic Framework Formulation:</strong> Establish generalized <span class="math inline">\(Q(I)\)</span> isotherms across highly diverse pedoclimatic sites to abstract the buffering capacity into universally comparable parameters (<span class="math inline">\(K_f\)</span> and <span class="math inline">\(n\)</span>). <em>Research Question:</em> Is the Swiss GRUD framework and its analytical proxies (<span class="math inline">\(P_{   ext{CO}_2}\)</span>, <span class="math inline">\(P_{AAE10}\)</span>) compliant with the broader European class concept presented by <span class="citation" data-cites="jordan-meilleOverviewFertilizerPRecommendations2012">Jordan-Meille et al. (<a href="#ref-jordan-meilleOverviewFertilizerPRecommendations2012" role="doc-biblioref">2012</a>)</span>, and do these empirical classes map meaningfully onto the underlying thermodynamic abstractions of physical desorption kinetics?</li>
<li><strong>Agronomic Prediction:</strong> Statistically evaluate the predictive power of the kinetic Activity Flux (<span class="math inline">\(J_0\)</span>) against relative crop yield and P-uptake. To isolate the chemical P-limitation from overarching climatic noise, agronomic outcomes will be normalized against a historical biological baseline (the historical maximum yield of non-limiting P treatments for specific site-crop combinations). <em>Hypothesis:</em> The thermodynamically corrected <span class="math inline">\(J_0\)</span> will significantly outperform standard static extractions.</li>
<li><strong>Mechanistic Validation:</strong> Propose a modified conceptual framework for radial transport to mathematically illustrate that the desorption rate acts as the primary limiting bottleneck restricting P-availability in the rhizosphere.</li>
</ol>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="sec-materials-and-methods" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Materials and Methods</h1>
<section id="sec-the-long-term-phosphorus-fertilization-experiment" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="sec-the-long-term-phosphorus-fertilization-experiment"><span class="header-section-number">2.1</span> The Long-Term Phosphorus Fertilization Experiment</h2>
<p>The soil samples for this thesis originate from a set of six long-term field trials in Switzerland, established by Agroscope between 1989 and 1992. The primary objective of these experiments was to validate and re-evaluate Swiss phosphorus (P) fertilization guidelines by assessing long-term crop yield responses to varying P inputs across different pedoclimatic conditions. A detailed description of the experimental design and site characteristics can be found in <span class="citation" data-cites="hirteYieldResponseSoil2021">Hirte et al. (<a href="#ref-hirteYieldResponseSoil2021" role="doc-biblioref">2021</a>)</span>.</p>
<p>The experiment was set up as a <strong>completely randomized block design</strong> with four field replications at each site. The core of the experiment consists of six fixed-plot treatments representing different P fertilization levels. These treatments were applied annually as triple superphosphate (TSP) before tillage and sowing. The application rates were strictly calibrated as percentages of the site- and crop-specific officially recommended P inputs (the Swiss GRUD norm): 0% (Zero), 33% (Deficit), 67% (Reduced), 100% (Norm), 133% (Elevated), and 167% (Surplus). This rigorous gradient ensures a massive divergence in cumulative P-balances across the 30-year timeframe, forcing distinct pedological responses.</p>
<p>Crucially, all other macronutrients—including Nitrogen (N), Potassium (K), and Magnesium (Mg)—were applied uniformly across all plots to prevent secondary yield limitations. However, it must be noted that these “non-limiting” applications were structurally calibrated to exactly 100% of their respective empirical Swiss GRUD recommendations, derived from the same matrix of operational soil tests and crop removal estimates criticized in this study. Consequently, the assumption that secondary nutrients were strictly non-limiting throughout the 30-year trial relies entirely on the epistemological validity of the empirical GRUD framework itself—a paradox that underscores the urgent need to transition toward mechanistic, site-specific nutrient modeling.</p>
<section id="crop-yield-phosphorus-uptake-and-balances" class="level3" data-number="2.1.1">
<h3 data-number="2.1.1" class="anchored" data-anchor-id="crop-yield-phosphorus-uptake-and-balances"><span class="header-section-number">2.1.1</span> Crop Yield, Phosphorus Uptake, and Balances</h3>
<p>While the fundamental experimental design and baseline data collection follow the protocols described in <span class="citation" data-cites="hirteYieldResponseSoil2021">Hirte et al. (<a href="#ref-hirteYieldResponseSoil2021" role="doc-biblioref">2021</a>)</span>, the specific processing of the agronomic variables for this study diverges to explicitly isolate the chemical P-limitation.</p>
<p>Crop yields were measured annually at harvest. Total fresh biomass was recorded, and representative subsamples were oven-dried to determine the absolute dry mass yield. Plant tissue phosphorus concentration (<span class="math inline">\(C_P\)</span>) was subsequently quantified from these dried subsamples. The total phosphorus uptake (<span class="math inline">\(P_{\text{uptake}}\)</span>) for each plot was calculated stoichiometrically as the product of the dry mass yield and the measured <span class="math inline">\(C_P\)</span>.</p>
<p>To accurately quantify the historical legacy of the different fertilization treatments, the <strong>Cumulative P Balance (<span class="math inline">\(Cum\_P\_{\text{bal}}\)</span>)</strong> was calculated for each individual plot. <span class="math inline">\(Cum\_P\_{\text{bal}}\)</span> is defined as the net sum of all P inputs (from the annual TSP fertilization) minus all P outputs (specifically, the P removed from the field via the harvested crop biomass) accumulated over the entire 30-year duration of the trial. This provides a direct, continuous metric of the anthropogenic P surplus or deficit, which drives the underlying thermodynamic buffering systems.</p>
</section>
</section>
<section id="analytical-workflow-and-data-integration" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="analytical-workflow-and-data-integration"><span class="header-section-number">2.2</span> Analytical Workflow and Data Integration</h2>
<p>To answer the research questions, the methodology is structured into three highly synchronized, modular steps mapping the raw data to the final agronomic predictions:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Modular workflow synchronizing data sources, extraction methods, and mathematical models.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="sec-experimental-sites" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="sec-experimental-sites"><span class="header-section-number">2.3</span> Experimental Sites</h2>
<p>The six experimental sites are located in the main crop-growing regions of Switzerland: <strong>Rümlang-Altwi (ALT)</strong>, <strong>Cadenazzo (CAD)</strong>, <strong>Ellighausen (ELL)</strong>, <strong>Grabs (GRA)</strong>, <strong>Oensingen (OEN)</strong>, and <strong>Zurich-Reckenholz (REC)</strong>. The key soil properties are summarized below.</p>
<div id="tbl-sites-corrected" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sites-corrected-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Soil characteristics of the six long-term experimental sites. Data adapted from Hirte et al.&nbsp;(2021).
</figcaption>
<div aria-describedby="tbl-sites-corrected-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 6%">
<col style="width: 27%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 21%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Site</th>
<th style="text-align: left;">Soil Type (WRB)</th>
<th style="text-align: right;">Clay (%)</th>
<th style="text-align: right;">Silt (%)</th>
<th style="text-align: right;">Sand (%)</th>
<th style="text-align: right;">Organic C (g/kg)</th>
<th style="text-align: right;">pH (H2O)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ALT</td>
<td style="text-align: left;">Calcaric Cambisol</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">7.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">CAD</td>
<td style="text-align: left;">Eutric Fluvisol</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">52</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">6.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ELL</td>
<td style="text-align: left;">Eutric Cambisol</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">6.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">GRA</td>
<td style="text-align: left;">Calcaric Fluvisol</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">49</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">8.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OEN</td>
<td style="text-align: left;">Gleyic-calc. Cambisol</td>
<td style="text-align: right;">37</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">7.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">REC</td>
<td style="text-align: left;">Eutric Gleysol</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">7.4</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Soil samples for this thesis were collected in the year 2022 from the topsoil layer (0-20 cm).</p>
</section>
<section id="sec-phosphorus-desorption-kinetics" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="sec-phosphorus-desorption-kinetics"><span class="header-section-number">2.4</span> Phosphorus Desorption Kinetics and Thermodynamics</h2>
<p>The laboratory extraction of phosphorus was based on the sequential kinetic principles established by <span class="citation" data-cites="flossmannExtractionMethodCharacterizing1982">Flossmann &amp; Richter (<a href="#ref-flossmannExtractionMethodCharacterizing1982" role="doc-biblioref">1982</a>)</span>, subsequently modified to capture high-resolution temporal kinetics and corrected to reflect thermodynamic activity.</p>
<section id="sec-adapted-kinetic-protocol-for-this-study" class="level3" data-number="2.4.1">
<h3 data-number="2.4.1" class="anchored" data-anchor-id="sec-adapted-kinetic-protocol-for-this-study"><span class="header-section-number">2.4.1</span> Adapted Kinetic Protocol for This Study</h3>
<p>To capture the desorption process with high temporal resolution while preserving the native soil matrix, a modified water-extraction protocol was employed:</p>
<ol type="1">
<li><strong>Pre-washing to Remove Initial Soluble P</strong>: 10 g of air-dried soil (sieved to &lt; 2 mm) was suspended in 200 ml of deionized water and horizontally shaken for 60 minutes at 120 rpm. The suspension was centrifuged for 15 minutes at 4000 rpm, and the supernatant containing the readily soluble P was completely decanted. The P concentration of this discarded fraction was not quantified in this study, as the primary objective was to reset the soil solution to <span class="math inline">\(P \approx 0\)</span> to isolate the subsequent solid-phase desorption kinetics. No soil was lost during decantation due to the highly compact nature of the pellet.</li>
<li><strong>Kinetic Extraction</strong>: Because the remaining saturated soil pellet was highly compacted from centrifugation, achieving full resuspension required rigorous shaking, meaning the reactive surface area was not perfectly constant at the exact onset of the experiment. The pellet was rapidly resuspended in 200 ml of fresh deionized water to initiate the desorption process. The suspension was shaken continuously. To capture the nonlinear initial release phase, 2 ml subsamples were drawn at precisely eight time points: 2, 4, 10, 15, 20, 30, 45, and 60 minutes.</li>
<li><strong>Analysis</strong>: Each subsample was immediately filtered through a 0.2 <span class="math inline">\(\mu\)</span>m membrane filter to halt desorption, and the stoichiometric concentration of orthophosphate (<span class="math inline">\(c(t)\)</span>) was determined colorimetrically using the malachite green method <span class="citation" data-cites="VanVeldhoven1987Malachite">(<a href="#ref-VanVeldhoven1987Malachite" role="doc-biblioref">Van Veldhoven &amp; Mannaerts, 1987</a>)</span>.</li>
</ol>
</section>
<section id="temporal-stability-of-amorphous-metal-oxides" class="level3" data-number="2.4.2">
<h3 data-number="2.4.2" class="anchored" data-anchor-id="temporal-stability-of-amorphous-metal-oxides"><span class="header-section-number">2.4.2</span> Temporal Stability of Amorphous Metal Oxides</h3>
<p>Although the kinetic parameters (<span class="math inline">\(k\)</span>) and geochemical structural variables (<span class="math inline">\(Fe_{\text{ox}}\)</span>, <span class="math inline">\(Al_{\text{ox}}\)</span>) were measured comprehensively in the year 2023, they were applied to the entire 26-year historical dataset. This is justified because oxalate-extractable iron and aluminum represent native, poorly-crystalline structural minerals rather than highly dynamic labile nutrient pools. Under constant arable management, these amorphous phases are widely recognized as pedologically stable over decadal timescales <span class="citation" data-cites="schwertmann1964differenzierung lookman1995geostatistical">(<a href="#ref-lookman1995geostatistical" role="doc-biblioref">Lookman et al., 1995</a>; <a href="#ref-schwertmann1964differenzierung" role="doc-biblioref">Schwertmann, 1964</a>)</span>. Thus, the 2023 measurements serve as robust, invariant site-means to characterize the fundamental sorption capacity of each experimental field.</p>
</section>
</section>
<section id="sec-statistical-analysis" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="sec-statistical-analysis"><span class="header-section-number">2.5</span> Statistical Analysis and Modeling</h2>
<p>All data processing, mathematical modeling, and visualization were conducted using the R programming language (v. 4.3.1) <span class="citation" data-cites="R-base">(<a href="#ref-R-base" role="doc-biblioref">R Core Team, 2026</a>)</span>. Primary packages included <code>nlme</code> <span class="citation" data-cites="R-nlme">(<a href="#ref-R-nlme" role="doc-biblioref">Pinheiro et al., 2026</a>)</span> for non-linear kinetic modeling, <code>lme4</code> <span class="citation" data-cites="R-lme4">(<a href="#ref-R-lme4" role="doc-biblioref">Bates et al., 2026</a>)</span> for linear mixed-effects modeling, and <code>deSolve</code> and <code>ReacTran</code> for partial differential equation solving.</p>
<section id="modeling-of-desorption-kinetics-and-the-desorption-velocity-v_0" class="level3" data-number="2.5.1">
<h3 data-number="2.5.1" class="anchored" data-anchor-id="modeling-of-desorption-kinetics-and-the-desorption-velocity-v_0"><span class="header-section-number">2.5.1</span> 1. Modeling of Desorption Kinetics and the Desorption Velocity (<span class="math inline">\(v_0\)</span>)</h3>
<p>To establish the foundational kinetic parameters, physical desorption curves were generated using a modified sequential extraction protocol based on <span class="citation" data-cites="flossmannExtractionMethodCharacterizing1982">Flossmann &amp; Richter (<a href="#ref-flossmannExtractionMethodCharacterizing1982" role="doc-biblioref">1982</a>)</span>. Soil samples were first pre-washed to discard readily soluble P, then resuspended in deionized water and continuously shaken. Subsamples were extracted across a high-resolution time series (2, 4, 10, 15, 20, 30, 45, and 60 minutes), and the orthophosphate concentration was determined colorimetrically using the malachite green method.</p>
<p><strong>Deriving the Desorption Rate Constant (<span class="math inline">\(k\)</span>):</strong> A non-linear mixed-effects model (<code>nlme</code>) was fitted to these high-resolution extraction curves. The desorption process was modeled as a hyperbolic, asymptotic saturation curve derived from the exact solution of the first-order rate equation:</p>
<p><span class="math display">\[
c(t) = c_{\text{max}} \times (1 - e^{-k \times t'})
\]</span></p>
<p>Where <span class="math inline">\(c(t)\)</span> is the desorbed P concentration at time <span class="math inline">\(t\)</span>, <span class="math inline">\(c_{\text{max}}\)</span> is the maximum size of the desorbable P pool (the asymptote), <span class="math inline">\(k\)</span> is the first-order desorption rate constant, and <span class="math inline">\(t'\)</span> is an adjusted time (<span class="math inline">\(t_{\text{min}} + 3 \text{ min}\)</span>) representing the empirically determined handling and resuspension time delay required to break apart the centrifuged pellet before true, uniform first-order desorption commenced. Sample-specific deviations were managed with the nested random effect structure <code>c_max + k ~ 1 | site / plot</code>, allowing both parameters to vary freely across sites and individual field plots.</p>
<p><strong>Upscaling via Pedotransfer Function (PTF):</strong> Because this labor-intensive 60-minute kinetic extraction cannot be retroactively applied to the entire 30-year historical STYCS archive, a fundamental <strong>Pedotransfer Function (PTF)</strong> was constructed to predict the rate constant for missing soils and treatments. To ensure the upscaling process remained rigorously grounded in established mechanistic physics rather than arbitrary empirical correlations, the PTF was structured upon the Arrhenius equation—where reaction rates are driven by the competing activation energies of dominant sorption surfaces. Accordingly, a linear model (<code>lm</code>) was trained to predict <span class="math inline">\(\ln(k)\)</span> using explicitly pedogenetic predictor variables: the natural log of the ratio of amorphous aluminum to iron oxides (<span class="math inline">\(\ln(Al_{\text{ox}} / Fe_{\text{ox}})\)</span>) and soil pH.</p>
<p>By anchoring the PTF to these inherently pedogenetic (treatment-independent) geochemical traits, we successfully extrapolated a predicted rate constant (<span class="math inline">\(k_{pred}\)</span>) for every spatial and temporal plot in the dataset.</p>
<p>From these predicted parameters, a novel proxy for agronomic availability, the <strong>Dynamic Desorption Velocity (<span class="math inline">\(v_0\)</span>)</strong>, was defined mathematically as the product of the predicted rate constant and the historically measured static concentration pool:</p>
<p><span class="math display">\[
v_0 = k_{pred} \cdot P_{\text{CO}_2}
\]</span></p>
</section>
<section id="thermodynamic-qi-isotherms-and-buffering-capacity" class="level3" data-number="2.5.2">
<h3 data-number="2.5.2" class="anchored" data-anchor-id="thermodynamic-qi-isotherms-and-buffering-capacity"><span class="header-section-number">2.5.2</span> 2. Thermodynamic <span class="math inline">\(Q(I)\)</span> Isotherms and Buffering Capacity</h3>
<p>To deduce the Phosphorus Buffering Capacity (PBC), a thermodynamic Quantity-Intensity (<span class="math inline">\(Q/I\)</span>) framework was constructed. The <span class="math inline">\(P_{\text{AAE10}}\)</span> extraction was utilized as the standard mass Quantity (<span class="math inline">\(Q\)</span>, <span class="math inline">\(\text{mg P kg}^{-1}\)</span>), while the Davies-corrected <span class="math inline">\(a_{\text{max}}\)</span> was utilized as the native Intensity (<span class="math inline">\(I\)</span>, <span class="math inline">\(\mu\text{M}\)</span>). It must be acknowledged that relying on <span class="math inline">\(P_{\text{AAE10}}\)</span> as a proxy for absolute thermodynamic Quantity carries inherent mechanistic limitations. As demonstrated by isotopic exchange kinetics (IEK) studies, the extraction fluid’s EDTA chelator actively dissolves non-exchangeable calcium phosphates—particularly in high-pH or high-CEC clays—leading to isotopic recovery rates as low as 25% <span class="citation" data-cites="demariaExchangeabilityPhosphateExtracted2005">(<a href="#ref-demariaExchangeabilityPhosphateExtracted2005" role="doc-biblioref">Demaria et al., 2005</a>)</span>. Furthermore, in heavily buffered clay soils, the chelator physically saturates when overwhelmed by exchangeable background cations. Once saturated, the test becomes entirely “blind” to any further thermodynamic <span class="math inline">\(Q\)</span>, artificially collapsing the measured <span class="math inline">\(\Delta Q\)</span> parameter.</p>
<p>The relationship between these variables across the varying fertilizer treatments at each site was parameterized using a log-linearized <strong>Freundlich Isotherm</strong> <span class="citation" data-cites="freundlich1906over">(<a href="#ref-freundlich1906over" role="doc-biblioref">Freundlich, 1906</a>)</span>, which is universally recognized for describing ion sorption on heterogeneous soil surfaces:</p>
<p><span class="math display">\[
Q = K_f \cdot I^{\frac{1}{n}}
\]</span></p>
<p>The apparent Phosphorus Buffering Capacity (PBC) for each specific site and state was then calculated analytically as the first derivative of the fitted Freundlich isotherm with respect to Intensity:</p>
<p><span class="math display">\[
\text{PBC} = \frac{dQ}{dI} = K_f \cdot \frac{1}{n} \cdot I^{\left(\frac{1}{n} - 1\right)}
\]</span></p>
<p><strong>Predicting Quantity via Pedotransfer Functions (PTF)</strong> To evaluate the practical scalability of these thermodynamic concepts, empirical Quantity (<span class="math inline">\(P_{\text{AAE10}}\)</span>) was modeled directly from Intensity using a log-linear mixed-effects model (<code>lme</code>):</p>
<p><span class="math display">\[
\ln(Q) = \beta_0 + \beta_I \cdot \ln(I) + \sum (\beta_j \cdot Z_j) + \ln(I) \sum (\beta_{int,j} \cdot Z_j) + u_{site} + u_{plot|site}
\]</span></p>
<ul>
<li><strong>The Covariates (<span class="math inline">\(Z_j\)</span>):</strong> Geochemical pedotransfer variables including soil fine texture (clay + silt), pH, <span class="math inline">\(C_{\text{org}}\)</span>, and exchangeable background cations (Ca, Mg, K). These are mechanistically justified as they structurally determine the density and binding energy of the soil’s sorption complexes (e.g., amorphous metal oxides and calcium carbonates).</li>
<li><strong>Interaction Terms:</strong> The covariates directly interact with Intensity because the <em>slope</em> of the Q/I isotherm (the buffer power) is fundamentally altered by these intrinsic geochemical properties.</li>
<li><strong>Random Effects (<span class="math inline">\(u_{year|site}\)</span>):</strong> Nested temporal and spatial intercepts designed to rigorously absorb unmeasured macro-climatic shifts and temporal biological chaos (e.g.&nbsp;frost timing, pest pressure, radiation) across the different experimental years, preventing pseudo-replication.</li>
</ul>
</section>
<section id="agronomic-normalization-controlling-pedoclimatic-noise" class="level3" data-number="2.5.3">
<h3 data-number="2.5.3" class="anchored" data-anchor-id="agronomic-normalization-controlling-pedoclimatic-noise"><span class="header-section-number">2.5.3</span> 3. Agronomic Normalization: Controlling Pedoclimatic Noise</h3>
<p>To rigorously separate underlying P-limitation from the immense baseline yield variance caused by pedoclimatic shifts and crop genetics, all raw yield and P-uptake metrics were normalized to a biologically strict empirical ceiling. For every combination of site, year, and crop, the absolute maximum value observed across all fertilization treatments was assigned as <span class="math inline">\(100\%\)</span> capacity.</p>
<p><span class="math display">\[
Y_{\text{rel}} = \frac{Y_{plot}}{\max_{treatment}(Y)_{site, year, crop}}
\]</span></p>
<p>Unlike using a specific fertilization label (e.g., the P166 treatment average), this method guarantees that the empirical Mitscherlich asymptote of <span class="math inline">\(1.0\)</span> is strictly bounded. It ensures that the unconstrained biological ceiling for that specific environment is defined by the actual absolute maximum biomass it produced, structurally eliminating random negative constraints (e.g., localized compaction or pest damage) that might artificially depress a specific treatment average. This mathematical operation removes the variance in the absolute biological ceiling, strictly isolating the chemical P-limitation from the overarching temporal pedoclimatic noise.</p>
</section>
<section id="bayesian-modeling-of-agronomic-outcomes" class="level3" data-number="2.5.4">
<h3 data-number="2.5.4" class="anchored" data-anchor-id="bayesian-modeling-of-agronomic-outcomes"><span class="header-section-number">2.5.4</span> 4. Bayesian Modeling of Agronomic Outcomes</h3>
<p>To test the core hypothesis and rigorously handle the structural heteroskedasticity inherent in agronomic field data, the biological response variables were modeled using Bayesian non-linear mixed-effects models via the <code>brms</code> package <span class="citation" data-cites="bürknerBrmsPackageBayesian2017">(<a href="#ref-bürknerBrmsPackageBayesian2017" role="doc-biblioref"><strong>bürknerBrmsPackageBayesian2017?</strong></a>)</span>. Unlike frequentist approaches that often suffer from algorithmic convergence failures (singularities) when fitting complex asymptotes near biological boundaries, the Bayesian framework allows us to define mathematically rigorous, biologically grounded priors to constrain the parameter space.</p>
<p>Due to the extreme non-linearity of the models—which multiply asymptotic kinetics by exponential environmental covariates across hundreds of random intercepts—the computational load was massive. The models were compiled and executed using the highly optimized <code>cmdstanr</code> backend <span class="citation" data-cites="gabry2023cmdstanr">(<a href="#ref-gabry2023cmdstanr" role="doc-biblioref"><strong>gabry2023cmdstanr?</strong></a>)</span>, enabling within-chain multi-threading to parallelize the Hamiltonian trajectories. All models utilized the No-U-Turn Sampler (NUTS) with four Markov Chain Monte Carlo (MCMC) chains, each running for 2000 iterations (1000 warmup), ensuring robust exploration of the posterior distributions.</p>
</section>
<section id="the-bayesian-fragility-of-the-mitscherlich-equation" class="level3" data-number="2.5.5">
<h3 data-number="2.5.5" class="anchored" data-anchor-id="the-bayesian-fragility-of-the-mitscherlich-equation"><span class="header-section-number">2.5.5</span> The Bayesian Fragility of the Mitscherlich Equation</h3>
<p>While the Mitscherlich equation (<span class="math inline">\(Y = A - (A - Y_0)e^{-c P}\)</span>) is the historical standard for modeling diminishing agronomic returns, it proved mathematically fragile within a Bayesian Hierarchical framework. When attempting to decompose the rate constant into pedoclimatic covariates (<span class="math inline">\(c_{\text{eff}} = c_{\text{base}} + \beta X\)</span>), the parameter space became algebraically unbounded. Random-walk sampling of extreme negative <span class="math inline">\(\beta\)</span> values instantly flipped the exponent from exponential decay to explosive exponential growth, generating mathematical singularities that shattered Hamiltonian Monte Carlo (HMC) convergence. Therefore, the Mitscherlich formulation was explicitly abandoned in favor of the Michaelis-Menten fractional geometry. The rational hyperbolic shape provides the exact same diminishing returns (a monotonically decreasing first derivative) but safely sequesters exponential covariates in the denominator, rigidly bounding the probability space and guaranteeing HMC convergence.</p>
<p>To aid clarity across the manuscript, the core model architectures are explicitly labeled. Alongside the mechanistic formulations, a heavily parameterized <strong>Heuristic Model</strong> was constructed as an empirical baseline. This heuristic model armed the Michaelis-Menten equations with a full suite of standard soil chemical metrics (pH, Clay fraction, Organic Carbon, and Exchangeable Calcium) alongside the pedoclimatic noise variables. This established a rigorous, highly-informed baseline against which the predictive power of the kinetic physics could be independently tested.</p>
<p><strong>1. The Yield Model (<span class="math inline">\(B_{Yield}\)</span>)</strong> The agronomic yield response was modeled using the Michaelis-Menten equation, bounding the unidentifiability of the intercept and asymptote by applying strict, crop-specific empirical limits (<span class="math inline">\(Y_0\)</span> and <span class="math inline">\(A\)</span>) extracted from the bounds of the actual data. The effective half-saturation constant (<span class="math inline">\(K_{\text{eff}}\)</span>) was dynamically modulated by pedoclimatic covariates:</p>
<p><span class="math display">\[
Yield = Y_0 + (A - Y_0) \frac{STP}{K_{\text{base}} \cdot \exp\left( \sum \beta_i \cdot Z_i \right) + STP}
\]</span></p>
<ul>
<li><strong>The Diffusion Bottleneck (<span class="math inline">\(\beta_{\text{invb}}\)</span>):</strong> The inverse physical buffer power (<span class="math inline">\(1/b\)</span>) acts as the primary transport penalty. Soils with high buffer power cannot replenish the root depletion zone fast enough via diffusion.</li>
<li><strong>The Kinetics (<span class="math inline">\(\beta_{k}\)</span>):</strong> The dynamic desorption rate (<span class="math inline">\(k\)</span>) directly decreases the half-saturation threshold by accelerating the physical resupply of P into the root depletion zone.</li>
<li><strong>Stoichiometric Co-Limitation (<span class="math inline">\(\beta_{N}\)</span>):</strong> Nitrogen fertilization fundamentally shifts the metabolic capacity of the crop.</li>
<li><strong>Pedoclimatic Noise (<span class="math inline">\(\beta_{Temp}, \beta_{Prec}\)</span>):</strong> Temperature and precipitation anomalies dictate physical soil moisture (governing diffusion transport) and the basic biological metabolic rate.</li>
</ul>
<p><strong>2. The Plant Uptake Model (<span class="math inline">\(B_{Uptake}\)</span>)</strong> Actual mass-flux of P into the plant was modeled using the same Michaelis-Menten biological limit, anchored at the origin (<span class="math inline">\(U_0 = 0\)</span>):</p>
<p><span class="math display">\[
Uptake = \frac{V_{max} \cdot \text{STP}}{K_{\text{base}} \cdot \exp\left( \sum \beta_i \cdot Z_i \right) + \text{STP}}
\]</span></p>
<p>Where the maximum uptake capacity (<span class="math inline">\(V_{max}\)</span>) acts as the biological asymptote, and the effective affinity is driven by the same critical covariates (<span class="math inline">\(\beta_{\text{invb}}, \beta_k, \beta_{\text{Temp}}, \beta_{\text{Prec}}\)</span>).</p>
<p><strong>3. The Tissue Concentration Model (<span class="math inline">\(B_{C_P}\)</span>)</strong> To expose the physiological dynamics of tissue concentrations, the apparent <span class="math inline">\(C_P\)</span> was modeled empirically using a <strong>Mitscherlich</strong> saturation curve. Because true Piper-Steenbjerg carbon dilution penalties (a drop in concentration at initial growth stages) were statistically undetectable across the pedoclimatic noise, the phenomena clearly dictate a simpler biological reality: A crop-specific baseline tissue concentration (<span class="math inline">\(C_{\text{min}}\)</span>), followed by an asymptotic <strong>Luxury Accumulation</strong> phase bounded by <span class="math inline">\(\Delta C\)</span>:</p>
<p><span class="math display">\[
C_P = C_{\text{min}} + \Delta C \cdot \left(1 - \exp\left(- c_{\text{eff}} \cdot \text{STP}\right)\right)
\]</span></p>
<ul>
<li><strong>Crop-Specific Baseline (<span class="math inline">\(C_{\text{min}}\)</span>):</strong> The fundamental, minimum tissue concentration required for the plant to physically exist, modeled as a fixed effect grouped by crop species (<code>~ crop - 1 + (1 | site/year)</code>).</li>
<li><strong>Luxury Accumulation (<span class="math inline">\(\Delta C\)</span>):</strong> Once basic metabolic needs are met, plants accumulate “luxury” P in their tissues up to a theoretical maximum.</li>
<li><strong>Accumulation Rate (<span class="math inline">\(c_{\text{eff}}\)</span>):</strong> This rate is significantly driven by pedoclimatic covariates and transport penalties, dictating how rapidly the soil can push excess phosphorus into the plant.</li>
</ul>
<p><strong>Bayesian Prior Elicitation and Biological Bounds</strong> To prevent mathematical singularities and ensure the parameter space remained strictly within physical reality, informative bounds were placed on the fundamental biological constants: - <strong>Baseline and Maximum Yield (<span class="math inline">\(Y_0, A\)</span>):</strong> Bounded strictly <span class="math inline">\(&gt; 0\)</span>. To resolve parameter unidentifiability in the flat plateaus of the data, highly informative empirical bounds were dynamically extracted from the dataset. For each crop, <span class="math inline">\(Y_0\)</span> was constrained around the absolute minimum observed yield, and <span class="math inline">\(A\)</span> around the absolute maximum, rigidly anchoring the vertical geometry of the curve. - <strong>Maximum Uptake Velocity (<span class="math inline">\(V_{\text{max}}\)</span>):</strong> Bounded <span class="math inline">\(&gt; 0\)</span> with <code>normal(30, 15)</code>, reflecting standard crop physiological limits (typically 15–45 kg P/ha). - <strong>Tissue Concentration Minimum (<span class="math inline">\(C_{\text{min}}\)</span>):</strong> Bounded <span class="math inline">\(&gt; 0\)</span> with <code>normal(1.5, 1.0)</code>, as a baseline tissue concentration of <span class="math inline">\(\approx 1.5 \text{ g/kg DM}\)</span> is universally required for basic cellular function in these crops. - <strong>Environmental Covariates (<span class="math inline">\(\beta\)</span>):</strong> Even with strict structural bounds, the simultaneous estimation of five exponential environmental covariates on the kinetic rate constant created a flat probability valley, preventing HMC convergence. To resolve this unidentifiability, an <strong>Empirical Bayes</strong> algebraic linearization technique was deployed. The Michaelis-Menten equation was algebraically rearranged into an affine linear model: <span class="math inline">\(Z = \ln((A - Y)/(Y - Y_0)) + \ln(\text{STP})\)</span>. By passing this linearized response into a frequentist linear mixed-effects model (<code>lmer</code>), exact empirical point estimates for the <span class="math inline">\(\beta\)</span> modifiers were calculated. These empirically derived coordinates were then injected into the Bayesian model as highly informative priors (e.g., <code>normal(0.776, 0.10)</code> for <span class="math inline">\(\beta_N\)</span>), dropping the Markov chains directly onto the global minimum and guaranteeing robust HMC convergence.</p>
<div id="tbl-variables-updated" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-variables-updated-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Comprehensive description of all response variables and covariates used in the thermodynamic and agronomic models, including their explicit preprocessing pipelines.
</figcaption>
<div aria-describedby="tbl-variables-updated-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 10%">
<col style="width: 21%">
<col style="width: 49%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Abbreviation</th>
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Description</th>
<th style="text-align: left;">Processing and Filtering</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(Y_{\text{rel}}\)</span></td>
<td style="text-align: left;">Relative Yield</td>
<td style="text-align: left;">Plot yield normalized by the local year’s maximum.</td>
<td style="text-align: left;">Normalized by the mean of the P166 treatment within the specific site <span class="math inline">\(\times\)</span> crop <span class="math inline">\(\times\)</span> year. Filtered for finite values.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(P_{\text{up, rel}}\)</span></td>
<td style="text-align: left;">Relative P Uptake</td>
<td style="text-align: left;">Plot P-uptake normalized by the local year’s maximum.</td>
<td style="text-align: left;">Normalized by the local P166 maximum. Rows with 0 uptake dropped.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\ln(P_{\text{AAE10}})\)</span></td>
<td style="text-align: left;">Log Quantity Pool</td>
<td style="text-align: left;">Standard mass of extractable P (AAE10 method).</td>
<td style="text-align: left;">Natural log transformed to ensure strictly positive predictions and stabilize variance in mixed models.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(P_{\text{CO}_2}\)</span></td>
<td style="text-align: left;">Empirical Intensity</td>
<td style="text-align: left;">Water-extractable P (<span class="math inline">\(CO_2\)</span> saturated).</td>
<td style="text-align: left;">Raw measured values. Log-transformed for PTF training.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(a_{\text{CO}_2}\)</span></td>
<td style="text-align: left;">Thermodynamic Intensity</td>
<td style="text-align: left;">Thermodynamic activity of the water pool.</td>
<td style="text-align: left;">Calculated via Davies equation accounting for ionic strength. Log-transformed.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(k_{\text{des}}\)</span></td>
<td style="text-align: left;">Desorption Rate Constant</td>
<td style="text-align: left;">First-order rate constant of P desorption.</td>
<td style="text-align: left;">Missing historical plots were imputed using a pedogenetic PTF trained on log(Al/Fe) + pH. Standardized (z-score).</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(v_{\text{des}}\)</span></td>
<td style="text-align: left;">Initial Desorption Velocity</td>
<td style="text-align: left;">Initial dynamic supply rate.</td>
<td style="text-align: left;">Calculated as product of predicted <span class="math inline">\(k\)</span> and empirical <span class="math inline">\(P_{ ext{CO}_2}\)</span>. Standardized (z-score).</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\text{PBC}^{-1}\)</span></td>
<td style="text-align: left;">Inverse Buffer Power</td>
<td style="text-align: left;">Inverse of the dynamic <span class="math inline">\(Q/I\)</span> slope (<span class="math inline">\(dI/dQ\)</span>).</td>
<td style="text-align: left;">Analytically derived from predicted Freundlich isotherms. Standardized (z-score).</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(Fe_{\text{ox}}, Al_{\text{ox}}\)</span></td>
<td style="text-align: left;">Amorphous Oxides</td>
<td style="text-align: left;">Amorphous Iron and Aluminum oxides.</td>
<td style="text-align: left;">Averaged into invariant site-means to remove management artifacts, log-transformed, and standardized.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\text{Clay} + \text{Silt}\)</span></td>
<td style="text-align: left;">Fine Texture</td>
<td style="text-align: left;">Sum of clay and silt fractions.</td>
<td style="text-align: left;">Log-transformed sum to linearize bounds, standardized. Missing values imputed with site-means.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\text{pH}_{\text{H}_2\text{O}}\)</span></td>
<td style="text-align: left;">Soil pH</td>
<td style="text-align: left;">Soil pH measured in water.</td>
<td style="text-align: left;">Standardized directly.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(C_{\text{org}}\)</span></td>
<td style="text-align: left;">Organic Carbon</td>
<td style="text-align: left;">Total organic carbon.</td>
<td style="text-align: left;">Log-transformed and standardized. Missing values imputed with site-means.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(Ca_{\text{ex}}, Mg_{\text{ex}}, K_{\text{ex}}\)</span></td>
<td style="text-align: left;">Exchangeable Cations</td>
<td style="text-align: left;">AAE10-extractable background cations.</td>
<td style="text-align: left;">Missing values imputed using site medians (or global medians if site missing). Log-transformed and standardized.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(T_{\text{anom}}, Pr_{\text{anom}}\)</span></td>
<td style="text-align: left;">Climate Anomalies</td>
<td style="text-align: left;">Juvenile phase temp/prec deviations.</td>
<td style="text-align: left;">Calculated as absolute deviation from the site’s long-term historical mean. Standardized.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(N_{\text{fert}}\)</span></td>
<td style="text-align: left;">Nitrogen Fertilizer</td>
<td style="text-align: left;">Total applied nitrogen fertilizer.</td>
<td style="text-align: left;">Standardized directly.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="mechanistic-modeling-of-the-rhizosphere-barber-cushman-modification" class="level3" data-number="2.5.6">
<h3 data-number="2.5.6" class="anchored" data-anchor-id="mechanistic-modeling-of-the-rhizosphere-barber-cushman-modification"><span class="header-section-number">2.5.6</span> 5. Mechanistic Modeling of the Rhizosphere (Barber-Cushman Modification)</h3>
<p>To mechanistically validate the field-scale statistical findings and visualize the limitations of static buffering capacity, a modified radial transport model based on Barber-Cushman principles <span class="citation" data-cites="barber1981soil">(<a href="#ref-barber1981soil" role="doc-biblioref">Barber &amp; Cushman, 1981</a>)</span> was constructed. Standard iterations of the Barber-Cushman model calculate radial diffusion using stoichiometric concentration (<span class="math inline">\(C_l\)</span>) and a static buffer power (<span class="math inline">\(b = \Delta Q / \Delta I\)</span>), effectively assuming instantaneous soil-solution equilibrium.</p>
<p>To reflect the kinetic bottlenecks identified in this study, the partial differential equation (PDE) for radial transport in cylindrical coordinates was modified. The driving gradient was kept as empirical concentration (<span class="math inline">\(c_l\)</span>), and the static buffer power was replaced with a dynamic, first-order kinetic source term (<span class="math inline">\(R_{\text{desorption}}\)</span>):</p>
<p><span class="math display">\[
\frac{\partial c_l}{\partial t} = D_e \left( \frac{\partial^2 c_l}{\partial r^2} + \frac{1}{r} \frac{\partial c_l}{\partial r} \right) + \frac{r_0 v_0}{r} \frac{\partial c_l}{\partial r} + R_{\text{desorption}}
\]</span></p>
<p>Where <span class="math inline">\(D_e\)</span> is the effective diffusion coefficient, <span class="math inline">\(r\)</span> is the radial distance, <span class="math inline">\(r_0\)</span> is the root radius, and <span class="math inline">\(v_0\)</span> is the water flux at the root surface. The kinetic source term resupplying the solution was defined using the experimentally derived parameters:</p>
<p><span class="math display">\[
R_{\text{desorption}} = k \cdot (c_{\text{max}} - c_l)
\]</span></p>
<p>Furthermore, the inner boundary condition at the root surface (<span class="math inline">\(r = r_0\)</span>) was upgraded to reflect a dual-affinity Michaelis-Menten uptake system <span class="citation" data-cites="michaelis1913kinetik">(<a href="#ref-michaelis1913kinetik" role="doc-biblioref">Michaelis &amp; Menten, 1913</a>)</span>, accounting for both high-affinity (PHT1) and low-affinity (LATS) transporter kinetics. The binding kinetics of these transporters are governed by the fundamental thermodynamic driving force of the substrate: its chemical activity (<span class="math inline">\(a\)</span>), not its total stoichiometric concentration (<span class="math inline">\(c\)</span>) <span class="citation" data-cites="Atkins2011Physical Minton2001Macromolecular">(<a href="#ref-Atkins2011Physical" role="doc-biblioref">Atkins &amp; Paula, 2011</a>; <a href="#ref-Minton2001Macromolecular" role="doc-biblioref">Minton, 2001</a>)</span>. The boundary condition was defined as:</p>
<p><span class="math display">\[
J_r = \frac{V_{max1} \cdot (c_l - c_{\text{min}})}{K_{m1} + (c_l - c_{\text{min}})} + \frac{V_{max2} \cdot (c_l - c_{\text{min}})}{K_{m2} + (c_l - c_{\text{min}})}
\]</span></p>
<p>The modified PDEs were solved numerically in R utilizing the <code>ReacTran</code> and <code>deSolve</code> packages to generate dynamic spatial profiles of the P-depletion zone over time.</p>
</section>
<section id="derivation-of-critical-thresholds-p_textcrit" class="level3" data-number="2.5.7">
<h3 data-number="2.5.7" class="anchored" data-anchor-id="derivation-of-critical-thresholds-p_textcrit"><span class="header-section-number">2.5.7</span> 6. Derivation of Critical Thresholds (<span class="math inline">\(P_{\text{crit}}\)</span>)</h3>
<p>To translate the mechanistic models into actionable agronomic metrics, the critical Soil Test Phosphorus (<span class="math inline">\(P_{\text{crit}}\)</span>) threshold was analytically derived from all three modeling frameworks. Rather than relying on arbitrary inflection points, each derivation represents a distinct physiological or agronomic paradigm:</p>
<p><strong>1. The Relative Yield Paradigm (The Production Target)</strong> Agronomically, <span class="math inline">\(P_{\text{crit}}\)</span> is classically defined as the STP required to achieve a specific operational threshold, commonly set as an <span class="math inline">\(x\%\)</span> relative yield target (<span class="math inline">\(q_Y\)</span>, e.g., 0.95). By setting the relative yield target to <span class="math inline">\(q_Y\)</span> in the full Mitscherlich equation (<span class="math inline">\(Y_{\text{rel}} = 1 - \exp(-c_{\text{eff}} \cdot (\text{STP} + E_{\text{base}}))\)</span>), the required soil concentration is extracted: <span class="math display">\[
P_{crit\_Y} = \frac{-\ln(1 - q_Y)}{c_{\text{eff}}} - E_{\text{base}}
\]</span> Where the effective rate constant incorporates the pedoclimatic penalties: <span class="math inline">\(c_{\text{eff}} = c_{\text{base}} \cdot \exp(\beta_{kin} \cdot \text{Kinetics} + \dots)\)</span>.</p>
<p><strong>2. The Tissue Concentration Paradigm (The Physiological Buffer)</strong> Because true Piper-Steenbjerg minima were statistically absent, the tissue concentration critical limit was redefined as the threshold necessary to guarantee the plant’s fundamental metabolic baseline (<span class="math inline">\(C_{\text{base}}\)</span>) <em>plus</em> a luxury reserve (<span class="math inline">\(\gamma\)</span>, representing an <span class="math inline">\(x\%\)</span> safety buffer). Solving the linear mixed-effects model (<span class="math inline">\(C_P = C_{\text{base}} + S_{\text{acc}} \cdot \text{STP}\)</span>) for the target <span class="math inline">\(C_{\text{base}}(1 + \gamma)\)</span> yields: <span class="math display">\[
P_{crit\_C} = \frac{\gamma \cdot C_{\text{base}}}{S_{\text{base}} + \beta_{v0} \cdot v_0 + \beta_{\text{invb}} \cdot \frac{1}{b}}
\]</span> This derivation explicitly demonstrates that soils with a faster desorption velocity (<span class="math inline">\(v_0\)</span>) or stronger buffer power (<span class="math inline">\(1/b\)</span>) create a steeper accumulation slope (<span class="math inline">\(S_{\text{acc}}\)</span>), inherently reducing the <span class="math inline">\(P_{\text{crit}}\)</span> required in the soil to safely buffer the crop against stress.</p>
<p><strong>3. The Relative Uptake Paradigm (The Mass-Transfer Limit)</strong> While yield integrates the entire season, instantaneous phosphorus uptake is strictly governed by Michaelis-Menten kinetics at the root surface. Defining a critical threshold as the STP required to reach an <span class="math inline">\(x\%\)</span> relative uptake target (<span class="math inline">\(q_{\text{up}}\)</span>) yields a direct relationship with the effective half-saturation constant (<span class="math inline">\(K_{\text{eff}}\)</span>): <span class="math display">\[
q_{\text{up}} = \frac{P_{crit\_up}}{K_{\text{eff}} + P_{crit\_up}} \implies P_{crit\_up} = \left(\frac{q_{\text{up}}}{1 - q_{\text{up}}}\right) K_{\text{eff}}
\]</span> Where <span class="math inline">\(K_{\text{eff}}\)</span> structurally expands upon the base crop affinity (<span class="math inline">\(K_m\)</span>) via the same physical kinetic bottlenecks identified in the field data.</p>
</section>
<section id="the-management-of-covariate-data-two-distinct-approaches" class="level3" data-number="2.5.8">
<h3 data-number="2.5.8" class="anchored" data-anchor-id="the-management-of-covariate-data-two-distinct-approaches"><span class="header-section-number">2.5.8</span> 7. The Management of Covariate Data: Two Distinct Approaches</h3>
<p>As established by <span class="citation" data-cites="hirteYieldResponseSoil2021">Hirte et al. (<a href="#ref-hirteYieldResponseSoil2021" role="doc-biblioref">2021</a>)</span>, incorporating pedoclimatic covariates is strictly necessary for obtaining robust, site- and crop-specific plant response models. However, the mathematical architecture used to integrate these covariates fundamentally impacts model stability and generalizability.</p>
<p>Across all models, the experimental structure was formalized using hierarchical random intercepts, <code>(1 | site/year)</code>, to absorb time-invariant site fertility and broader climatic potential. Consequently, the main effects of our chosen covariates act exclusively as <em>deviations</em> modulating the base phosphorus affinity (<span class="math inline">\(K_{\text{base}}\)</span>). To benchmark model generalization and test the risk of overparameterization, we evaluated two fundamentally different architectures for incorporating these soil constraints:</p>
<p><strong>1. The Heuristic Approach</strong> We first established a “Null” baseline using a Michaelis-Menten geometry, explicitly abandoning the classical Mitscherlich asymptote which systematically failed Hamiltonian convergence due to the algebraically unbounded nature of its exponential parameterization. The Heuristic approach then expanded this baseline by directly injecting six raw pedoclimatic variables (soil pH, clay content, organic carbon, calcium, and site-normalized temperature and precipitation anomalies) as simultaneous exponential modifiers on <span class="math inline">\(K_{\text{base}}\)</span>.</p>
<p><strong>2. The Mechanistic Approach</strong> Rather than directly feeding raw soil chemistry into the agronomic model, the Mechanistic approach first condensed this pedoclimatic complexity through non-linear desorption kinetics (following the fundamental principles of Flossmann &amp; Richter, 1982). This yielded exactly two fundamental thermodynamic parameters—the diffusion bottleneck (<span class="math inline">\(1/b\)</span>) and the desorption rate (<span class="math inline">\(k\)</span>)—which were then deployed alongside management variables (temperature, precipitation, and nitrogen fertilization) to predict crop response.</p>
<p><strong>Model Evaluation</strong> By condensing raw covariates into physical constraints (<span class="math inline">\(b\)</span> and <span class="math inline">\(k\)</span>), we sought to determine if the Mechanistic approach generalizes more robustly to unseen data, or if the direct inclusion of all raw soil variables in the Heuristic model provides superior predictive power. Models were rigorously evaluated and compared based on their Hamiltonian stability (<span class="math inline">\(\hat{R}\)</span>), root-mean-square error (RMSE), pseudo-<span class="math inline">\(R^2\)</span> (marginal and conditional), and out-of-sample expected log predictive density utilizing Leave-One-Out Cross-Validation (LOOIC).</p>
<p>For an agronomic and environmental science context, it is crucial to distinguish between a model’s ability to “fit” the data it was trained on (RMSE, <span class="math inline">\(R^2\)</span>) versus its ability to safely predict entirely new, unseen field sites (LOOIC). LOOIC operates by iteratively hiding one observation at a time, forcing the model to predict the missing data point; models with a lower (more negative) LOOIC generalize better to the real world. During this cross-validation process, we also calculate the effective number of parameters (<span class="math inline">\(p_{loo}\)</span>). In complex agronomic models with multiple interacting pedoclimatic covariates, an inflated <span class="math inline">\(p_{loo}\)</span> metric acts as a direct diagnostic warning for “overfitting”—indicating that the model is hallucinating relationships and memorizing random micro-climate noise rather than capturing universally applicable physical mechanisms.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
</section>
<section id="results" class="level1 page-columns page-full" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Results</h1>
<section id="the-blind-spot-of-empirical-soil-tests" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="the-blind-spot-of-empirical-soil-tests"><span class="header-section-number">3.1</span> The Blind Spot of Empirical Soil Tests</h2>
<p>Standard empirical soil tests (STP) rely on chemical extraction to quantify a static “stock” of available phosphorus. However, these extractions are inherently blind to the dynamic physical constraints that govern how quickly that phosphorus can actually move through the soil matrix to the root surface.</p>
<p>As demonstrated in <a href="#fig-kinetic-vs-empirical" class="quarto-xref">Figure&nbsp;1</a>, soils that are classified identically by empirical extractions (<span class="math inline">\(P_{CO_2}\)</span>, <span class="math inline">\(P_{AAE10}\)</span>) can exhibit drastically different physical properties. A soil with a theoretically “adequate” <span class="math inline">\(P_{CO_2}\)</span> extraction value of 1.0 mg/kg can possess a diffusion restriction proxy (<span class="math inline">\(1/b\)</span>) ranging anywhere from 0.05 to 0.45, and a desorption rate (<span class="math inline">\(k\)</span>) that varies just as wildly.</p>
<p>Ultimately, there appears to be no distinct connection between empirical STP measurements and fundamental kinetic variables. For any given STP value, a soil can exhibit a wide range of differing kinetic and diffusive properties, meaning these standard extractions do not inherently reflect the physical supply mechanisms of the soil matrix.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-kinetic-vs-empirical" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-kinetic-vs-empirical-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-kinetic-vs-empirical-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-kinetic-vs-empirical-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Distribution of long-term P balance across standard empirical tests (<span class="math inline">\(P_{CO_2}\)</span>, <span class="math inline">\(P_{AAE10}\)</span>) versus physical desorption kinetics (Buffer capacity <span class="math inline">\(b\)</span>, Diffusion proxy <span class="math inline">\(1/b\)</span>, and Desorption rate <span class="math inline">\(k\)</span>). Red indicates a positive P balance (surplus), while green indicates a negative P balance (deficit). Note the lack of correlation between the empirical ‘stock’ and the physical ‘flow’ properties.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="plant-response-variables" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="plant-response-variables"><span class="header-section-number">3.2</span> Plant Response Variables</h2>
<p>When evaluating predictive performance, it is important to strictly distinguish between crop yield and actual P uptake. While both serve as agronomic response variables, yield inherently exhibits greater variance and environmental noise. This instability occurs because the internal phosphorus concentration of the crop tissue (<span class="math inline">\(C_P\)</span>) can fluctuate significantly—driven by luxury consumption in P-rich environments or physiological dilution during rapid biomass accumulation. Consequently, P uptake provides a more direct, mechanistically linked reflection of soil P availability than raw yield, which acts as a heavily buffered secondary response.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-yield-vs-uptake" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-yield-vs-uptake-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-yield-vs-uptake-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-yield-vs-uptake-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Total Yield versus Annual P Uptake grouped by crop type. The polynomial trend lines highlight the non-linear decoupling of yield from uptake at higher availability levels, driven by fluctuating internal plant P concentrations (<span class="math inline">\(C_P\)</span>).
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="yield-model-comparison" class="level2 page-columns page-full" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="yield-model-comparison"><span class="header-section-number">3.3</span> Yield model comparison</h2>
<p>To evaluate whether thermodynamic kinetic parameters offer an advantage over empirical supply classes, we compared the predictive power of five non-linear mixed-effects models against a null model. All models accounted for site-specific and crop-specific yield ceilings via hierarchical random effects (<span class="math inline">\(1 | \text{site/year}\)</span>). They differed in how the base availability (<span class="math inline">\(K_{base}\)</span>) of the STP (<span class="math inline">\(P_{CO_2}\)</span> or <span class="math inline">\(P_{AAE10}\)</span>) was modulated.</p>
<div class="cell page-columns page-full">
<div id="tbl-yield-comparison" class="cell quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-tbl figure page-columns page-full">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-yield-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4
</figcaption>
<div aria-describedby="tbl-yield-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<div class="cell-output-display column-page">
<table class="do-not-create-environment caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 32%">
<col style="width: 6%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 6%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: left;">Pedoclimatic Covariates</th>
<th style="text-align: left;">RMSE</th>
<th style="text-align: left;"><span class="math inline">\(R^2_{Marg}\)</span></th>
<th style="text-align: left;"><span class="math inline">\(R^2_{Cond}\)</span></th>
<th style="text-align: left;">LOOIC</th>
<th style="text-align: left;"><span class="math inline">\(p_{loo}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Base Model CO2</td>
<td style="text-align: left;">(None)</td>
<td style="text-align: left;">12.36</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">79256</td>
<td style="text-align: left;">130.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Base Model AAE10</td>
<td style="text-align: left;">(None)</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Null Model</td>
<td style="text-align: left;">(None)</td>
<td style="text-align: left;">11.50</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">77999</td>
<td style="text-align: left;">231.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Heuristic CO2</td>
<td style="text-align: left;">pH, Clay, Corg, Ca, Temp, Prec</td>
<td style="text-align: left;">10.56</td>
<td style="text-align: left;">0.702</td>
<td style="text-align: left;">0.929</td>
<td style="text-align: left;">77721</td>
<td style="text-align: left;">1104.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Heuristic AAE10</td>
<td style="text-align: left;">pH, Clay, Corg, Ca, Temp, Prec</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mechanistic</td>
<td style="text-align: left;">1/b, k, N, Temp, Prec</td>
<td style="text-align: left;">10.73</td>
<td style="text-align: left;">0.701</td>
<td style="text-align: left;">0.931</td>
<td style="text-align: left;">76636</td>
<td style="text-align: left;">247.2</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>While the Heuristic <span class="math inline">\(CO_2\)</span> model achieved the lowest root mean square error (RMSE = 10.56) on the training data, the Bayesian leave-one-out cross-validation (<span class="math inline">\(LOOIC\)</span>) indicated that this performance was associated with severe overfitting to the six pedoclimatic covariates (<span class="math inline">\(p_{loo} = 1104.8\)</span>).</p>
<p>In contrast, the Mechanistic model, which constrained <span class="math inline">\(K_{base}\)</span> strictly to the physical limits of the desorption rate (<span class="math inline">\(k\)</span>) and buffer capacity (<span class="math inline">\(1/b\)</span>), generalized better (<span class="math inline">\(\Delta LOOIC = -1086\)</span> vs.&nbsp;Heuristic <span class="math inline">\(CO_2\)</span>; <span class="math inline">\(p_{loo} = 247.2\)</span>).</p>
<p>However, neither the empirical STPs nor the kinetic parameters demonstrated strong predictive power for absolute crop yield when compared to the Null model (<span class="math inline">\(\Delta LOOIC = -1364\)</span> vs.&nbsp;Mechanistic). This confirms that short-term agronomic yield is overwhelmingly dominated by local micro-climates and crop biology, rendering the specific physical P-supply mechanism secondary for short-term predictions.</p>
<p>To evaluate true predictive power, we relied on the Expected Log Predictive Density (ELPD) calculated via Bayesian leave-one-out cross-validation (LOO-CV). Unlike in-sample error metrics such as RMSE, which invariably reward overly complex models, ELPD rigorously penalizes models that overfit to local noise. The difference in ELPD (<span class="math inline">\(\Delta\)</span>ELPD) serves as a relative measure of out-of-sample performance. This metric fundamentally exposes models that achieve low training error merely by hallucinating relationships with non-causal covariates.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-yield-looic" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-yield-looic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-yield-looic-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-yield-looic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Out-of-Sample Predictive Performance (LOO) of yield models relative to the best model. Error bars represent <span class="math inline">\(\pm 2\)</span> standard errors of the ELPD difference.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-yield-conditional" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-yield-conditional-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-yield-conditional-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-yield-conditional-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Conditional effects of <span class="math inline">\(P_{CO_2}\)</span> STP on predicted yield across crops. The Mechanistic model (blue) produces constrained asymptotic responses bounded by physical desorption parameters. The Heuristic model (orange) demonstrates massive uncertainty and flat average responses, indicating that its predictive power was inappropriately shifted to pedoclimatic covariates.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-yield-shrinkage" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-yield-shrinkage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-yield-shrinkage-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-yield-shrinkage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Posterior uncertainty (shrinkage) of the crop-specific base affinity (<span class="math inline">\(K_{base}\)</span>) for the Mechanistic and Heuristic yield models. The massive 95% credible intervals for the Heuristic model indicate severe overfitting and an inability to constrain the fundamental agronomic relationship, whereas the Mechanistic model is tightly constrained by physical desorption kinetics.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="phosphorus-uptake-c_p-model-comparison" class="level2 page-columns page-full" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="phosphorus-uptake-c_p-model-comparison"><span class="header-section-number">3.4</span> Phosphorus Uptake (<span class="math inline">\(C_P\)</span>) model comparison</h2>
<p>We repeated the identical model hierarchy to predict total plant phosphorus uptake rather than dry matter yield.</p>
<div class="cell page-columns page-full">
<div id="tbl-uptake-comparison" class="cell quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-tbl figure page-columns page-full">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-uptake-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5
</figcaption>
<div aria-describedby="tbl-uptake-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<div class="cell-output-display column-page">
<table class="do-not-create-environment caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 32%">
<col style="width: 5%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 6%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: left;">Pedoclimatic Covariates</th>
<th style="text-align: left;">RMSE</th>
<th style="text-align: left;"><span class="math inline">\(R^2_{Marg}\)</span></th>
<th style="text-align: left;"><span class="math inline">\(R^2_{Cond}\)</span></th>
<th style="text-align: left;">LOOIC</th>
<th style="text-align: left;"><span class="math inline">\(p_{loo}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Base Model CO2</td>
<td style="text-align: left;">(None)</td>
<td style="text-align: left;">0.70</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">21539</td>
<td style="text-align: left;">118.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Base Model AAE10</td>
<td style="text-align: left;">(None)</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Null Model</td>
<td style="text-align: left;">(None)</td>
<td style="text-align: left;">0.65</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">20053</td>
<td style="text-align: left;">144.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Heuristic CO2</td>
<td style="text-align: left;">pH, Clay, Corg, Ca, Temp, Prec</td>
<td style="text-align: left;">0.63</td>
<td style="text-align: left;">0.540</td>
<td style="text-align: left;">0.791</td>
<td style="text-align: left;">19374</td>
<td style="text-align: left;">163.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Heuristic AAE10</td>
<td style="text-align: left;">pH, Clay, Corg, Ca, Temp, Prec</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mechanistic</td>
<td style="text-align: left;">1/b, k, N, Temp, Prec</td>
<td style="text-align: left;">0.64</td>
<td style="text-align: left;">0.534</td>
<td style="text-align: left;">0.782</td>
<td style="text-align: left;">19820</td>
<td style="text-align: left;">160.8</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>In a stark divergence from the yield models, the Heuristic <span class="math inline">\(CO_2\)</span> model demonstrated the highest predictive power both in-sample (RMSE = 0.62) and out-of-sample (LOOIC = 19374).</p>
<p>Crucially, the Heuristic uptake model did not suffer from the severe overfitting observed in the yield predictions; its effective number of parameters (<span class="math inline">\(p_{loo} = 163.2\)</span>) was nearly identical to the strictly constrained Mechanistic model (<span class="math inline">\(p_{loo} = 160.7\)</span>). This indicates that the pedoclimatic covariates (pH, Clay, Temperature, Precipitation) were capturing true, generalizable physical signals rather than memorizing local noise.</p>
<p>This phenomenological divergence is biologically consistent. While absolute dry matter yield is a highly confounded metric capped by dozens of non-phosphorus environmental factors, luxury plant P-uptake (<span class="math inline">\(C_P\)</span>) is tightly coupled to the physical diffusion of P to the roots and active root metabolism. Therefore, allowing local soil properties and climate variables to flexibly modulate the apparent availability of the empirical STP (<span class="math inline">\(P_{CO_2}\)</span>) legitimately improves the prediction of biological P-acquisition over purely thermodynamic bounds.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-uptake-looic" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-uptake-looic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-uptake-looic-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-uptake-looic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Out-of-Sample Predictive Performance (LOO) of P-Uptake models. In stark contrast to dry matter yield, the Heuristic model genuinely outperforms the Mechanistic constraints out-of-sample.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-uptake-conditional" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-uptake-conditional-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-uptake-conditional-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-uptake-conditional-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Conditional effects of STP on P-Uptake. Because the pedoclimatic covariates capture true signal for P-acquisition, the Heuristic model produces stable, physically meaningful response curves without hallucinating.
</figcaption>
</figure>
</div>
</div>
</div>
<p>To fully understand <em>why</em> the pedoclimatic covariates induce severe overfitting in the yield models but provide genuine predictive power for P-uptake, we can examine the estimated effect sizes (and their uncertainties) across both agronomic responses (<a href="#fig-covariate-effects" class="quarto-xref">Figure&nbsp;8</a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-covariate-effects" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-covariate-effects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-covariate-effects-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-covariate-effects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Forest plot of estimated covariate modifiers on base P availability (<span class="math inline">\(K_{base}\)</span>) for both Yield and P-Uptake. The Heuristic model’s reliance on soil pH, clay, and organic carbon to predict yield exhibits massive uncertainty (wide 95% CIs) and instability, characteristic of overfitting. In contrast, the effects on P-Uptake are tightly constrained and biologically meaningful.
</figcaption>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="discussion" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Discussion</h1>
<div style="page-break-after: always;"></div>
</section>
<section id="conclusion" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Conclusion</h1>
<div style="page-break-after: always;"></div>
</section>
<section id="acknowledgments" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Acknowledgments</h1>
<p>Without my wife I could not have again and again found the energy and time to work on my deeply personally motivated thesis. While she gave me the space to work, she tended to our little son, who in return with his intruiging way of demanding and negotiating play-time, attention and proximity, constantly earthed and reminded me of our dependence on others. The idea for this thesis came from many lengthy discussions with Frank Liebisch, where he, although being so busy, invested so much time in my development to an agronomist during my internship. He endured over and over my harsh critique on the nature and issues of agronomic research, and understood my drustration on the limitations posed on agronomic researchers, while still giving me hope in the possibility of progress and knowledge gain. It is not common, that a master student can choose his own topic and methodology for his master thesis, Emmanuel Frossard agreed immediately upon hearing from my idea. He knew that the task I set myself was difficult and extensive, but he not only showed confidence in my ability to grow on the pitfalls and issues, he would always remind me with his charactersitic words. “Il faut avoir le courage”, that acknowloding one’s own limitation and ignorance and simultaneously making falsifiable claims and to stand for them, is a cardinal attitude I can grow into. The support of Frank and Emmanuel went beyond their responsibility as specialists, I will never forget the kindness and patience shown to me, knowing that I behaved often spiky and frustrated, when my abstract and often idealistic considerations met the hard reality of soil-chemisty-measurements. Gratiously Emmanuel Frossard provided me access to the group’s laboratory, where Laurie Schönholzer supported me heavily, developing the protocol for my experiments. She not only shared her professional knowledge, but would also educate me on the code how to properly prepare and clean a lab. My wife reports, that I behave differently since then when it comes to our household. I benefited increadibly from this thesis. Lukas Graz introduced me to Quarto and helped me setting up a workflow, that is both safe in terms of data-loss and reproducible. He relentlessly explained me the pitfalls when using hierarchical models, aided in the selection of the effect-structure and taught me both as a friend and specialist invaluable lessons, how to structure and effiently write R-code, approaching complex real data. He encouraged me over and over, this thesis would not have been possible without him. I would also like to acknowledge the use of Google’s Gemini language model in the preparation of this thesis. It served as a valuable programming assistant for debugging R and LaTeX code, and as an editorial tool for improving language, formatting, and the overall structure of the manuscript, particularly in the discussion and conclusion sections.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="references" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-Atkins2011Physical" class="csl-entry" role="listitem">
Atkins, P., &amp; Paula, J. de. (2011). <em>Physical chemistry for the life sciences</em> (2nd ed.). Oxford University Press.
</div>
<div id="ref-barber1981soil" class="csl-entry" role="listitem">
Barber, S. A., &amp; Cushman, J. H. (1981). Nitrogen uptake model for agronomic crops. In I. K. Iskandar (Ed.), <em>Modeling wastewater renovation land treatment</em> (pp. 382–409). Wiley.
</div>
<div id="ref-R-lme4" class="csl-entry" role="listitem">
Bates, D., Maechler, M., Bolker, B., Walker, S., Jagan, M., &amp; Ly, A. (2026). <em>lme4: Linear mixed-effects models using eigen and S4</em>. <a href="https://github.com/lme4/lme4/">https://github.com/lme4/lme4/</a>
</div>
<div id="ref-Brady2016Soils" class="csl-entry" role="listitem">
Brady, N. C., &amp; Weil, R. R. (2016). <em>The nature and properties of soils</em> (15th ed.). Pearson.
</div>
<div id="ref-demariaExchangeabilityPhosphateExtracted2005" class="csl-entry" role="listitem">
Demaria, P., Flisch, R., Frossard, E., &amp; Sinaj, S. (2005). Exchangeability of phosphate extracted by four chemical methods. <em>Z. Pflanzenernähr. Bodenk.</em>, <em>168</em>(1), 89–93. <a href="https://doi.org/10.1002/jpln.200421463">https://doi.org/10.1002/jpln.200421463</a>
</div>
<div id="ref-fardeau1996dynamics" class="csl-entry" role="listitem">
Fardeau, J.-C. (1996). Dynamics of phosphate in soils. An isotopic outlook. <em>Fertilizer Research</em>, <em>45</em>, 91–100.
</div>
<div id="ref-flossmannExtractionMethodCharacterizing1982" class="csl-entry" role="listitem">
Flossmann, R., &amp; Richter, D. (1982). <em>Extraction method for characterizing the kinetics of phosphorus release from solid soil to soil solution.</em>
</div>
<div id="ref-FAL1996Methodenbuch" class="csl-entry" role="listitem">
Forschungsanstalt für Agrarökologie und Landbau (FAL). (1996). <em>Methodenbuch für boden-, pflanzen- und nährstoffanalysen</em>. FAL.
</div>
<div id="ref-freundlich1906over" class="csl-entry" role="listitem">
Freundlich, H. (1906). <span>Ü</span>ber die <span>A</span>dsorption in <span>L</span><span>ö</span>sungen. <em>Zeitschrift f<span>ü</span>r Physikalische Chemie</em>, <em>57</em>(1), 385–470.
</div>
<div id="ref-Frossard2000Processes" class="csl-entry" role="listitem">
Frossard, E., Condron, L. M., Oberson, A., Sinaj, S., &amp; Fardeau, J. C. (2000). Processes governing phosphorus availability in temperate soils. <em>Journal of Environmental Quality</em>, <em>29</em>(1), 15–23. <a href="https://doi.org/10.2134/jeq2000.00472425002900010003x">https://doi.org/10.2134/jeq2000.00472425002900010003x</a>
</div>
<div id="ref-galletEffectPhosphateFertilization2003" class="csl-entry" role="listitem">
Gallet, A., Flisch, R., Ryser, J.-P., Frossard, E., &amp; Sinaj, S. (2003). Effect of phosphate fertilization on crop yield and soil phosphorus status. <em>Z. Pflanzenernähr. Bodenk.</em>, <em>166</em>(5), 568–578. <a href="https://doi.org/10.1002/jpln.200321081">https://doi.org/10.1002/jpln.200321081</a>
</div>
<div id="ref-gustafssonModelingCompetitiveAnion2001" class="csl-entry" role="listitem">
Gustafsson, J. P. (2001). Modeling competitive anion adsorption on oxide minerals and an allophane-containing soil. <em>European Journal of Soil Science</em>, <em>52</em>(4), 639–653. <a href="https://doi.org/10.1046/j.1365-2389.2001.00407.x">https://doi.org/10.1046/j.1365-2389.2001.00407.x</a>
</div>
<div id="ref-gustafssonVisualMINTEQ32014" class="csl-entry" role="listitem">
Gustafsson, J. P. (2014). <em>Visual MINTEQ 3.1</em> [Computer software]. <a href="https://vminteq.lwr.kth.se/">https://vminteq.lwr.kth.se/</a>
</div>
<div id="ref-hirteYieldResponseSoil2021" class="csl-entry" role="listitem">
Hirte, J., Richner, W., Orth, B., Liebisch, F., &amp; Flisch, R. (2021). Yield response to soil test phosphorus in <span>Switzerland</span>: <span>Pedoclimatic</span> drivers of critical concentrations for optimal crop yields using multilevel modelling. <em>Science of The Total Environment</em>, <em>755</em>, 143453. <a href="https://doi.org/10.1016/j.scitotenv.2020.143453">https://doi.org/10.1016/j.scitotenv.2020.143453</a>
</div>
<div id="ref-jordan-meilleOverviewFertilizerPRecommendations2012" class="csl-entry" role="listitem">
Jordan-Meille, L., Rubæk, G. H., Ehlert, P. A. I., Genot, V., Hofman, G., Goulding, K., Recknagel, J., Provolo, G., &amp; Barraclough, P. (2012). An overview of fertilizer-<span>P</span> recommendations in <span>Europe</span>: Soil testing, calibration and fertilizer recommendations. <em>Soil Use and Management</em>, <em>28</em>(4), 419–435. <a href="https://doi.org/10.1111/j.1475-2743.2012.00453.x">https://doi.org/10.1111/j.1475-2743.2012.00453.x</a>
</div>
<div id="ref-lookman1995geostatistical" class="csl-entry" role="listitem">
Lookman, R., Desmet, J., Grobet, P., Merckx, R., &amp; Vlassak, K. (1995). A geostatistical assessment of the regional distribution of phosphate sorption capacity parameters (feox and alox) in northern belgium. <em>Geoderma</em>, <em>66</em>(3-4), 285–296.
</div>
<div id="ref-michaelis1913kinetik" class="csl-entry" role="listitem">
Michaelis, L., &amp; Menten, M. L. (1913). Die <span>K</span>inetik der <span>I</span>nvertinwirkung. <em>Biochemische Zeitschrift</em>, <em>49</em>, 333–369.
</div>
<div id="ref-Minton2001Macromolecular" class="csl-entry" role="listitem">
Minton, A. P. (2001). The influence of macromolecular crowding and macromolecular confinement on biochemical reactions in physiological media. <em>Journal of Biological Chemistry</em>, <em>276</em>(14), 10577–10580.
</div>
<div id="ref-Nye2000Solute" class="csl-entry" role="listitem">
Nye, P. H., &amp; Tinker, P. B. (2000). <em>Solute movement in the rhizosphere</em>. Oxford University Press.
</div>
<div id="ref-Olsen1954" class="csl-entry" role="listitem">
Olsen, S. R., Cole, C. V., Watanabe, F. S., &amp; Dean, L. A. (1954). <em>Estimation of available phosphorus in soils by extraction with sodium bicarbonate</em> (Circular No. 939). United States Department of Agriculture.
</div>
<div id="ref-R-nlme" class="csl-entry" role="listitem">
Pinheiro, J., Bates, D., &amp; R Core Team. (2026). <em>Nlme: Linear and nonlinear mixed effects models</em>. <a href="https://svn.r-project.org/R-packages/trunk/nlme/">https://svn.r-project.org/R-packages/trunk/nlme/</a>
</div>
<div id="ref-R-base" class="csl-entry" role="listitem">
R Core Team. (2026). <em>R: A language and environment for statistical computing</em>. R Foundation for Statistical Computing. <a href="https://doi.org/10.32614/R.manuals">https://doi.org/10.32614/R.manuals</a>
</div>
<div id="ref-schwertmann1964differenzierung" class="csl-entry" role="listitem">
Schwertmann, U. (1964). Differenzierung der <span>E</span>isenoxide des <span>B</span>odens durch <span>E</span>xtraktion mit <span>A</span>mmoniumoxalat-l<span>ö</span>sung. <em>Zeitschrift f<span>ü</span>r Pflanzenern<span>ä</span>hrung, D<span>ü</span>ngung, Bodenkunde</em>, <em>105</em>(3), 194–202.
</div>
<div id="ref-Sposito2008Chemistry" class="csl-entry" role="listitem">
Sposito, G. (2008). <em>The chemistry of soils</em> (2nd ed.). Oxford University Press.
</div>
<div id="ref-steinfurthThresholdsTargetPhosphorus2022" class="csl-entry" role="listitem">
<span class="nocase">Steinfurth, K., Börjesson, G., Denoroy, P., Eichler-Löbermann, B., Gans, W., Heyn, J., Hirte, J., Huyghebaert, B., Jouany, C., Koch, D., Merbach, I., Mokry, M., Mollier, A., Morel, C., Panten, K., Peiter, E., Poulton, P. R., Reitz, T., Rubæk, G. H., … Buczko, U.</span> (2022). Thresholds of target phosphorus fertility classes in <span>European</span> fertilizer recommendations in relation to critical soil test phosphorus values derived from the analysis of 55 <span>European</span> long-term field experiments. <em>Agriculture, Ecosystems &amp; Environment</em>, <em>332</em>, 107926. <a href="https://doi.org/10.1016/j.agee.2022.107926">https://doi.org/10.1016/j.agee.2022.107926</a>
</div>
<div id="ref-VanVeldhoven1987Malachite" class="csl-entry" role="listitem">
Van Veldhoven, P. P., &amp; Mannaerts, G. P. (1987). Inorganic and organic phosphorus in the scheldt estuary. <em>Estuarine, Coastal and Shelf Science</em>, <em>25</em>(6), 755–765.
</div>
</div>
<div style="page-break-after: always;"></div>
<div style="page-break-after: always;"></div>
</section>
<section id="appendix-thermodynamic-correction-of-p_-extco_2-extractions" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Appendix: Thermodynamic Correction of <span class="math inline">\(P_{    ext{CO}_2}\)</span> Extractions</h1>
<section id="a.1.-intrinsic-ionic-strength-of-the-p_-extco_2-extractant" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="a.1.-intrinsic-ionic-strength-of-the-p_-extco_2-extractant"><span class="header-section-number">8.1</span> A.1. Intrinsic Ionic Strength of the <span class="math inline">\(P_{    ext{CO}_2}\)</span> Extractant</h2>
<p>Standard static soil test methods rely on the operational extraction of phosphorus. Strong extractants (e.g., Olsen P, P-AAE10) possess inherently high ionic strengths that dominate the soil matrix, complicating absolute thermodynamic comparisons without complex modeling. In contrast, the <span class="math inline">\(P_{  ext{CO}_2}\)</span> method utilizes a very weak extractant: water saturated with carbon dioxide at atmospheric pressure (1 atm) and 25 °C.</p>
<p>To demonstrate that the <span class="math inline">\(P_{    ext{CO}_2}\)</span> extractant adopts the native ionic strength of the soil, we calculate the intrinsic ionic strength (<span class="math inline">\(I\)</span>) of the pure extractant.</p>
<p>According to Henry’s Law, the concentration of dissolved <span class="math inline">\(CO_2\)</span> (denoted as <span class="math inline">\(H_2CO_3^*\)</span>) is: <span class="math display">\[[H_2CO_3^*] = K_H \times P_{CO_2}\]</span> Given Henry’s constant (<span class="math inline">\(K_H \approx 0.034 \text{ M atm}^{-1}\)</span>) and <span class="math inline">\(P_{CO_2} = 1 \text{ atm}\)</span>, the molarity of dissolved <span class="math inline">\(CO_2\)</span> is approximately <span class="math inline">\(0.034 \text{ M}\)</span>.</p>
<p>The primary ionic species generated arise from the first dissociation of carbonic acid: <span class="math display">\[H_2CO_3^* \rightleftharpoons H^+ + HCO_3^-\]</span> Using the acid dissociation constant (<span class="math inline">\(K_{a1} = 4.46 \times 10^{-7}\)</span> at 25 °C): <span class="math display">\[K_{a1} = \frac{[H^+][HCO_3^-]}{[H_2CO_3^*]}\]</span> Because <span class="math inline">\([H^+] \approx [HCO_3^-]\)</span>, we can solve for the bicarbonate concentration: <span class="math display">\[[HCO_3^-] = \sqrt{4.46 \times 10^{-7} \times 0.034} \approx 1.23 \times 10^{-4} \text{ M}\]</span></p>
<p>The intrinsic ionic strength (<span class="math inline">\(I\)</span>) of the extractant is defined as: <span class="math display">\[I = \frac{1}{2} \sum (C_i z_i^2)\]</span> <span class="math display">\[I = \frac{1}{2} \left( (1.23 \times 10^{-4} \times (+1)^2) + (1.23 \times 10^{-4} \times (-1)^2) \right) \approx 0.00012 \text{ M}\]</span></p>
<p>This intrinsic ionic strength (<span class="math inline">\(\approx 0.12 \text{ mM}\)</span>) is negligible compared to native agricultural soil solutions (which typically range from <span class="math inline">\(10\)</span> to <span class="math inline">\(50 \text{ mM}\)</span>). Therefore, the final ionic strength of the <span class="math inline">\(P_{    ext{CO}_2}\)</span> extract is primarily dictated by the dissolved soluble salts of the specific soil being analyzed.</p>
</section>
<section id="a.2.-justification-for-the-davies-equation" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="a.2.-justification-for-the-davies-equation"><span class="header-section-number">8.2</span> A.2. Justification for the Davies Equation</h2>
<p>Because the <span class="math inline">\(P_{    ext{CO}_2}\)</span> extract adopts the native ionic composition of the soil, reading the orthophosphate concentrations against an <span class="math inline">\(I=0\)</span> (distilled water) calibration curve introduces systematic error. The fundamental thermodynamic driving force for P-availability is the chemical <strong>activity</strong>, not the stoichiometric concentration.</p>
<p>To correct for this, an activity coefficient (<span class="math inline">\(\gamma\)</span>) must be applied. While the Pitzer equations are the standard method for high-ionic-strength solutions (<span class="math inline">\(I &gt; 0.5 \text{ M}\)</span>, such as the P-AAE10 extractant), the ionic strength of native agricultural soil solutions is typically much lower (<span class="math inline">\(I &lt; 0.1 \text{ M}\)</span>).</p>
<p>In this low-to-moderate ionic strength regime, the <strong>Davies equation</strong> (an empirical extension of the Debye-Hückel theory) is highly accurate and does not require complex, ion-specific interaction parameters.</p>
<p>The Davies equation calculates the activity coefficient (<span class="math inline">\(\gamma\)</span>) as follows: <span class="math display">\[\log_{10}(\gamma) = -A z^2 \left( \frac{\sqrt{I}}{1 + \sqrt{I}} - 0.3 I \right)\]</span> Where: * <strong><span class="math inline">\(A\)</span></strong> is a temperature-dependent constant (<span class="math inline">\(\approx 0.509 \text{ L}^{0.5} \text{mol}^{-0.5}\)</span> for water at 25 °C). * <strong><span class="math inline">\(z\)</span></strong> is the charge of the ion in question (for orthophosphate, <span class="math inline">\(z\)</span> depends on pH, predominantly <span class="math inline">\(-1\)</span> for <span class="math inline">\(H_2PO_4^-\)</span> and <span class="math inline">\(-2\)</span> for <span class="math inline">\(HPO_4^{2-}\)</span>). * <strong><span class="math inline">\(I\)</span></strong> is the total ionic strength of the extracted solution, calculated from the measured concentrations of major cations (<span class="math inline">\(Ca^{2+}, Mg^{2+}, K^+\)</span>).</p>
</section>
<section id="a.3.-implementation-of-thermodynamic-correction" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="a.3.-implementation-of-thermodynamic-correction"><span class="header-section-number">8.3</span> A.3. Implementation of Thermodynamic Correction</h2>
<p>To assess the theoretical P-Intensity (<span class="math inline">\(I\)</span>) and formulate the Phosphorus Buffering Capacity (PBC), the operationally defined <span class="math inline">\(P_{   ext{CO}_2}\)</span> concentrations are converted to thermodynamic activities using the following sequential steps:</p>
<ol type="1">
<li><strong>Determine Total Ionic Strength (<span class="math inline">\(I\)</span>):</strong> Using the measured cation concentrations from the extracts. <span class="math display">\[I = \frac{1}{2} \left( [K^+] + 4[Ca^{2+}] + 4[Mg^{2+}] + \dots \right)\]</span></li>
<li><strong>Calculate the Activity Coefficient (<span class="math inline">\(\gamma\)</span>):</strong> Applying the Davies equation based on the sample’s specific <span class="math inline">\(I\)</span>.</li>
<li><strong>Compute Chemical Activity:</strong> <span class="math display">\[\text{Activity} (P) = [P_{CO_2}] \times \gamma\]</span></li>
</ol>
<p>By standardizing the measurements to their corrected thermodynamic activity, we remove the analytical bias introduced by varying soil salinity and pedoclimatic history, allowing for an absolute comparison of P-Intensity across all STYCS experimental sites. ## A.4 Supplementary Materials and Reproducibility</p>
<p>This Master’s thesis was produced using a fully reproducible workflow with the <strong>Quarto</strong> publishing system. All data, R scripts, and analytical notebooks used to generate the figures, tables, and results presented in this work are openly available.</p>
<p>The complete project can be cloned from the author’s GitHub repository, which contains the raw data, the R code for the kinetic and statistical models, and the Quarto source files.</p>
<p><strong>GitHub Repository URL:</strong> <a href="https://github.com/ptochosgeorgos/Article-P-desorption-kinetics"><strong>[https://github.com/ptochosgeorgos/Article-P-desorption-kinetics]</strong></a></p>
<p>A rendered version of the full project, including the analytical notebooks that document the development process, is also available as a GitHub Pages website at the following URL:</p>
<p><strong>GitHub Pages Site URL:</strong> <a href="https://ptochosgeorgos.github.io/Article-P-desorption-kinetics/"><strong>[https://ptochosgeorgos.github.io/Article-P-desorption-kinetics/]</strong></a></p>
<p>This approach ensures full transparency and allows for the complete replication of the findings presented in this thesis.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ptochosgeorgos\.github\.io\/Article-P-desorption-kinetics\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>