# Read the file
lines <- readLines("notebooks/cluster_bayesian_offload.R")

# We want to append the P_balance analysis at the end.
new_code <- c(
  "",
  "#######################################################################",
  "# P-BALANCE MODELS & EVALUATION",
  "#######################################################################",
  "# Convert normative P2O5 requirement to P (kg/ha)",
  "D_env$P_up_norm <- D_env$fert_P2O5_NORM * 0.4364",
  "",
  "# Define GRUD Multipliers for Supply Classes",
  "# Usually A=1.5, B=1.2, C=1.0, D=0.5, E=0",
  "grud_multipliers <- c('A' = 1.5, 'B' = 1.2, 'C' = 1.0, 'D' = 0.5, 'E' = 0.0)",
  "D_env$M_class_CO2 <- grud_multipliers[as.character(D_env$Supply_class_CO2)]",
  "D_env$M_class_AAE10 <- grud_multipliers[as.character(D_env$Supply_class_AAE10)]",
  "",
  "# True annual P balance",
  "D_env$annual_P_bal_true <- D_env$fert_P_tot - D_env$annual_P_uptake",
  "",
  "# GRUD Base Models (Deterministic, based on norms and multipliers)",
  "D_env$annual_P_bal_pred_CO2 <- D_env$P_up_norm * (D_env$M_class_CO2 - 1)",
  "D_env$annual_P_bal_pred_AAE10 <- D_env$P_up_norm * (D_env$M_class_AAE10 - 1)",
  "",
  "# For Heuristic and Mechanistic, predict the uptake from the fitted models",
  "pred_heur <- predict(mod_heur_U, newdata = D_env)",
  "pred_mech <- predict(mod_mech_U, newdata = D_env)",
  "D_env$annual_P_bal_pred_heur <- D_env$fert_P_tot - pred_heur[, 'Estimate']",
  "D_env$annual_P_bal_pred_mech <- D_env$fert_P_tot - pred_mech[, 'Estimate']",
  "",
  "# Aggregate cumulatively to 30-year balances per plot",
  "library(dplyr)",
  "pbal_agg <- D_env %>%",
  "  group_by(site, plot_nr) %>%",
  "  summarise(",
  "    Cum_P_bal_true = sum(annual_P_bal_true, na.rm = TRUE),",
  "    Cum_P_bal_CO2 = sum(annual_P_bal_pred_CO2, na.rm = TRUE),",
  "    Cum_P_bal_AAE10 = sum(annual_P_bal_pred_AAE10, na.rm = TRUE),",
  "    Cum_P_bal_Heur = sum(annual_P_bal_pred_heur, na.rm = TRUE),",
  "    Cum_P_bal_Mech = sum(annual_P_bal_pred_mech, na.rm = TRUE),",
  "    .groups = 'drop'",
  "  )",
  "",
  "# Compute R2 and RMSE for each approach",
  "calc_metrics <- function(true, pred) {",
  "  valid <- !is.na(true) & !is.na(pred)",
  "  t_val <- true[valid]",
  "  p_val <- pred[valid]",
  "  rmse <- sqrt(mean((t_val - p_val)^2))",
  "  r2 <- 1 - sum((t_val - p_val)^2) / sum((t_val - mean(t_val))^2)",
  "  return(list(RMSE = rmse, R2 = r2))",
  "}",
  "",
  "res_pbal <- list(",
  "  CO2 = calc_metrics(pbal_agg$Cum_P_bal_true, pbal_agg$Cum_P_bal_CO2),",
  "  AAE10 = calc_metrics(pbal_agg$Cum_P_bal_true, pbal_agg$Cum_P_bal_AAE10),",
  "  Heur = calc_metrics(pbal_agg$Cum_P_bal_true, pbal_agg$Cum_P_bal_Heur),",
  "  Mech = calc_metrics(pbal_agg$Cum_P_bal_true, pbal_agg$Cum_P_bal_Mech),",
  "  data = pbal_agg",
  ")",
  "",
  "saveRDS(res_pbal, '../data/pbalance_results.rds')",
  "print('P-Balance evaluation completed and saved to pbalance_results.rds')"
)

# Insert the new code before the final print statement of the original script if we want,
# or just append it to the very end.
cat(c(lines, new_code), file = "notebooks/cluster_bayesian_offload.R", sep = "\n")
