import re

qmd_path = 'notebooks/qi_modelling1.qmd'
r_path = 'notebooks/qi_modelling1.R'

with open(qmd_path, 'r') as f:
    qmd_content = f.read()

with open(r_path, 'r') as f:
    r_content = f.read()

# Find the yield chunk in R
# The R script was generated by purl, so it has:
# ## ----mitscherlich-yield-models, fig.width=10, fig.height=4--------------------
# ...
# ## ----forest-plot-c-drivers, fig.width=8, fig.height=5-------------------------

# Let's extract the yield chunk from R
r_yield_chunk = r_content.split('## ----mitscherlich-yield-models, fig.width=10, fig.height=4--------------------')[1].split('## ----forest-plot-c-drivers, fig.width=8, fig.height=5-------------------------')[0]
# Remove leading empty lines
r_yield_chunk = r_yield_chunk.lstrip('\n')

# Now find the chunk in qmd
# ```{r mitscherlich-yield-models, fig.width=10, fig.height=4}
# ...
# ```
qmd_pattern = re.compile(r'```{r mitscherlich-yield-models, fig.width=10, fig.height=4}\n.*?\n```', re.DOTALL)

new_qmd_chunk = '```{r mitscherlich-yield-models, fig.width=10, fig.height=4}\n' + r_yield_chunk.strip() + '\n```'

new_qmd_content = qmd_pattern.sub(new_qmd_chunk, qmd_content)

with open(qmd_path, 'w') as f:
    f.write(new_qmd_content)

print("Synchronized mitscherlich-yield-models chunk from .R to .qmd")
